- ansible-requirements.yaml
> upgrade community libvirt to 1.0.2

- .gitignore
- examples/inventories/advanced_inventory_example.yaml
- inventories/seapath.yaml
- playbooks/ci_boot_machine_from_pxe.yaml
- playbooks/ci_configure_cluster.yaml
- playbooks/ci_configure_hosts.yaml
- playbooks/ci_restart_machines.yaml
- playbooks/ci_start_machine.yaml
- playbooks/ci_stop_machine.yaml
- playbooks/cluster_setup_ceph.yaml
- playbooks/cluster_setup_configure_hosts.yaml
- playbooks/cluster_setup_kernel_params.yaml
- playbooks/cluster_setup_libvirt.yaml
- playbooks/cluster_setup_main.yaml
- playbooks/cluster_setup_network.yaml
- playbooks/replace_machine_remove_machine_from_cluster.yaml
- playbooks/replace_machine_setup_new_machine.yaml
- playbooks/replace_machine_shrink_mgr.yaml
- playbooks/replace_machine_shrink_mon.yaml
- playbooks/replace_machine_shrink_osd.yaml
- playbooks/replace_machine_shrink_pacemaker.yaml
- playbooks/tasks/restart_machine.yaml
- playbooks/tasks/start_machine.yaml
- playbooks/tasks/stop_machine.yaml
- scripts/get_osd.py
- templates/libvirt_pool.xml.j2
- templates/secret.xml.j2
Add playbooks to replace a machine from SEAPATH cluster.
> Replace machine

- examples/inventories/advanced_inventory_example.yaml
- inventories/seapath.yaml
- playbooks/ci_boot_machine_from_pxe.yaml
- playbooks/ci_configure_hosts.yaml
- playbooks/ci_set_efi_boot_entries.yaml
- playbooks/cluster_setup_static_ip.yaml
- playbooks/replace_machine_setup_new_machine.yaml
- scripts/add_seapath_boot_entries.sh
Update Ansible files to support UEFI machines.
> UEFI support

- rollback.md
basic documentation for how to rollback a change with seapath-debian
> [debian] create rollback.md file

- src/debian/00-schedrt.conf
> [debian] sysctl: change printk kernel parameters

- roles/debian/hypervisor/tasks/main.yml
> [Debian] Solves bug in "solving os-prober huge latency" commit

- src/debian/rules.v4
> iptables: forbid access to localbr

- .gitignore
- .gitmodules
- playbooks/test_deploy_cukinia.yaml
- playbooks/test_deploy_cukinia_tests.yaml
Add playbooks to deploy the test framework [Cukinia](https://github.com/savoirfairelinux/cukinia) with security tests in SEAPATH Debian.
Cukinia tests are imported from [meta-seapath](https://github.com/seapath/meta-seapath).
> Add Cukinia in Debian

- roles/debian/hypervisor/tasks/main.yml
> Modif cmdline isolcpus

- roles/debian/hypervisor/tasks/main.yml
- src/debian/ptp_docker/compose-ptp_docker.yml
- src/debian/ptp_docker/ptpdocker.service
- src/debian/ptp_docker/ptpstatus.service
- src/debian/ptp_vsock.py
- src/debian/ptp_vsock.service
Instead of an apache service running on a specific bridge (for which we need iptables rules), we propose a vsock interface.
> [debian] Add VSOCK interface to get ptp status

- templates/vm/votp_vm.xml.j2
- templates/vm/votp_vm_rt_isolated.xml.j2
> [debian] VM template: pc-q35-3.1 + vsock

- inventories/seapath_cluster_definition_example.yml
- vars/ceph_group_vars/all.yml
> [debian] Add ansible variable for osd_memory_target override

- playbooks/cluster_setup_configure_hosts.yaml
- playbooks/cluster_setup_configure_hugepages.yaml
- playbooks/cluster_setup_kernel_params.yaml
Modify playbooks to set the number of hugepages and restart the associated service if needed.
> Hugepages configuration

- playbooks/cluster_setup_network.yaml
- templates/ovs_configuration.json.j2
Use Open vSwtich to create the cluster bridge.
> playbooks/cluster_setup_network: create the cluster bridge

- inventories/seapath.yaml
- playbooks/cluster_setup_network.yaml
- templates/00-ptp.netdev.j2
- templates/01-ptp.network.j2
- vars/network_vars.yml
If a PTP VLAN is defined configure and enable the PTP.
> playbooks/cluster_setup_network: configure PTP

- roles/debian/tasks/main.yml
> bash history: add timestamp information

- roles/debian/hypervisor/tasks/main.yml
> enable ptp_vsock systemd service at boot

- .github/workflows/ci-debian.yml
- playbooks/ci_the_one_playbook.yaml
- playbooks/test_run_cukinia.yaml
Add the github action that calls the ci and configure cukinia and playbooks to run with it
> Add github action that call the ci on debian-main

- roles/debian/tasks/main.yml
Add a conditional block and also install the server CA.
> roles/debian: refactor syslog keys

- .github/workflows/ci-debian.yml
- README.adoc
The ci is now separated in three parts
This pr update Action to fit the new version on the CI repository
> Update ci acording to changes on the ci repo

- playbooks/test_deploy_cukinia_tests.yaml
Create /etc/cukinia/cukinia.conf symlink according to the machine type (observer or hypervisor).
Update Cukinia submodule ref.
> playbooks/test_deploy_cukinia_tests: create cukinia.conf using symlink

- .github/workflows/ansible-lint.yml
- README.adoc
- playbooks/cluster_setup_ceph.yaml
- playbooks/cluster_setup_ha.yaml
- playbooks/cluster_setup_keys.yaml
- playbooks/cluster_setup_libvirt.yaml
- playbooks/cluster_setup_network.yaml
- playbooks/replace_machine_shrink_pacemaker.yaml
- playbooks/vm_deploy.yaml
- roles/debian-hardening/handlers/main.yml
- roles/debian-hardening/tasks/main.yml
- roles/debian/hypervisor/tasks/main.yml
- roles/seapath_import_vm_disk/tasks/main.yml
- roles/seapath_manage_disks/tasks/main.yml
- roles/seapath_vm_manage/tasks/add_vm.yml
- roles/seapath_vm_manage/tasks/main.yml
Add ansible lint as github action
> Ansible lint

- src/debian/90-sysctl-hardening.conf
> Anssi bp 028 r9

- roles/debian-hardening/vars/main.yml
* update cukinia-tests for bp-028-r11
* add security=yama in boot cmdline
> Anssi Bp 028 r11

- roles/debian-hardening/tasks/main.yml
- src/debian/mktmpdir.sh
* Add private tmpdir for each user
> Bp 028 r55

- README.adoc
Change some step names to fit the new version on the CI with the latency test. Also fix formatting
> README.adoc: Update CI description

- inventories/seapath_cluster_definition_example.yml
- inventories/seapath_standalone_definition_example.yml
- playbooks/cluster_setup_network.yaml
- roles/debian/hypervisor/tasks/main.yml
- templates/sriov_network_pool.xml.j2
- load sriov sysfs rules
- load kernel module
- add libvirt network pool
- add apparmor sriov permission for libvirt
> Add SR-IOV support

- inventories/seapath_cluster_definition_example.yml
- inventories/seapath_standalone_definition_example.yml
- playbooks/test_run_latency_tests.yaml
- roles/debian/tasks/main.yml
- roles/debian/templates/sources.list.j2
If the Ansible list variable apt_repo is defined, used it to configure apt repositories.
> roles/debian: configure apt repositories

- playbooks/test_run_cukinia.yaml
Also bump cukinia-tests git submodules to get cluster tests fixes.
> Run cluster tests

- inventories/seapath_cluster_definition_example.yml
- playbooks/cluster_setup_network.yaml
- playbooks/tasks/sriov_pool.yaml
- templates/sriov_network_pool.xml.j2
Before this commit, only one network pool was created in the network playbook.
> [debian] SRIOV: use dict to create network pools

- playbooks/test_deploy_cukinia.yaml
This patch is now integrated in cukinia.
Resolve #219
> playbooks/test_deploy_cukinia: remove cukinia_kconf

- .github/workflows/ansible-lint-weekly.yml
- .github/workflows/ci-yocto-weekly.yml
Change the weekly date to have a badge sooner than yesterday.
> workflows: change weekly date

- inventories/seapath_cluster_definition_example.yml
- inventories/seapath_standalone_definition_example.yml
Regroup variables by theme and add comments.
> inventories: refactor SEAPATH inventories samples

- roles/debian/tasks/main.yml
- src/debian/backup-restore/restore_vm.sh.j2
We are now using the "livemigration_user" variable.
> restore.sh: remove hardcoded "virtu" user

- inventories/seapath_standalone_definition_example.yml
Following d95ad864cfe2d8b2690784fe3c65e5a53c9465a6, the standalone inventory had not been updated. This commit fixes that.
> standalone inventory: add multiple NTP

- library/cluster_vm.py
- playbooks/cluster_setup_deploy_vms.yaml
- playbooks/tasks/deploy_vm.yaml
- add live_migration options to vm_manager ansible module
- (bonus) cluster_deploy_vms: add missing "become: true" to playbook
> add live_migration options to vm_manager ansible module

- playbooks/cluster_setup_keys.yaml
- playbooks/cluster_setup_prerequisdebian.yaml
- roles/debian/tasks/main.yml
- src/debian/69-lvm.rules
Patch for a known limitation of lvm2:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018730
in prevision of debian 12.
> softraid: make lvm2 activate the degraded raid in initramfs

- inventories/seapath_cluster_definition_example.yml
- inventories/seapath_standalone_definition_example.yml
- templates/timemaster.conf.j2
Make delay_mechanism and network_transport configurable. The current configuration is great but difficult to setup without hardware assistant.
> templates/timemaster.conf.j2: more configuration options

- inventories/seapath_vm_definition_example.yml
- templates/vm/guest.xml.j2
Fix bug in vm template when the variable cpuset is not given
> Cpuset bug fix

- examples/inventories/vms_inventory_example.yaml
- templates/vm/guest.xml.j2
Fix vm template failure when cpu set is not defined
> Cpuset bug fix yocto

- .gitignore
- README.adoc
- ansible-lint.conf
- playbooks/update_machine_cluster.yaml
- playbooks/update_machine_standalone.yaml
- swu_images/README
- vm_images/README
Add playbook to update a machine in the cluster or standalone.
> Add update playbooks

- templates/ovs_configuration.json.j2
Refactor OVS configuration setup by providing default values for 'ovs_bridges' and 'ignored_bridges'.
> ovs_configuration.json.j2: fix default option for OVS configuration

- .github/workflows/ci-yocto.yml
Add a task to deploy 2 VMs, one isolated and rt, and the other non
isolated and non rt.
> ci-yocto.yml: add deploy vms task

- README.adoc
The ansible-lint link has been changed.
> Update ansible-lint badge

- .github/workflows/ci-yocto.yml
> ci-yocto.yml: add VMs tests

- roles/debian/hypervisor/tasks/main.yml
- roles/debian/tasks/main.yml
- src/debian/grub.d/10-isolcpus.cfg.j2
As requested https://github.com/seapath/ansible/pull/398#discussion_r1500334433
> Move isolcpus customization to /etc/default/grub.d

- inventories/seapath_standalone_definition_example.yml
The hypervisors group was not present in the inventory.
> inventories: correct standalone example

- inventories/seapath_vm_definition_example.yml
- templates/vm/guest.xml.j2
- Update 'guest.xml.j2' template to include disk configuration for the virtual machine.
- Add local_disk variable to indicate the VM disk list, when you're on the standalone version and it's not managed by VM manager.
> Add disk configuration

- playbooks/cluster_setup_network.yaml
- templates/00-ptp.netdev.j2
- templates/79-ptp.network.j2
- templates/79-ptp_interface.network.j2
- templates/timemaster.conf.j2
- templates/timemaster.service.j2
- vars/network_vars.yml
- add timemaster configuration and service template files
- add timemaster configuration to the cluster_setup_network.yaml playbook
> Add timemaster 

- inventories/seapath_cluster_definition_example.yml
- inventories/seapath_standalone_definition_example.yml
\+ update standalone example inventory
> inventory: missing extract option in archive upload example

- playbooks/cluster_setup_debian.yaml
Add a task to verify we are configuring the target with a compatible Ansible git branch.  #434
> cluster_setup_debian: add a branch verification

- playbooks/cluster_setup_main.yaml
Add a task to verify we are configuring the target with a compatible Ansible git branch.
> cluster_setup_main: add a branch verification

- inventories/README.md
- Correct simple readme syntax
- Bump cukinia-tests commits
> Correct readme syntax

- src/tuned/tuned.conf.j2
----
see commit 8d0a65e
tuned default to FF4, we change it back to FF10
----
we bump vm_manager
> tuned: change rcu priority back to 10 + bump vm_manager

- src/debian/ptpstatus/ptpstatus.sh
To avoid copyright issues, we reimplemented the ptpstatus script. It provides the same output files but, it is less verbose. The refresh interval is now a parameter of the script.
Fix #476
> ptpstatus: reimplementation our own script

- inventories/seapath_cluster_definition_example.yml
- playbooks/cluster_setup_network.yaml
The machine hostname is based on inventory_hostname, which cannot be customized through a variable. This change adds the option to change hostnames.
> Add hostname variable

- playbooks/test_deploy_cukinia_tests.yaml
Some of the requirements were done but not tested.
> Add cukinia tests for BP28

- .github/workflows/ci-debian.yml
Bump cukinia-tests and CI to use the new cukinia ID feature
> Use cukinia id debian

- examples/inventories/vms_inventory_example.yaml
- playbooks/deploy_vms_standalone.yaml
- templates/vm/guest.xml.j2
Add the standalone main disk automatically to the libvirt XML.
> Add standalone main disk during VM creation

- playbooks/ci_all_machines_tests.yaml
- scripts/ci_system_info.py
Addition of a script to retrieve information
from the system on which the CI will run.
> scripts/ci_system_info.py: add system info fetch

- .github/workflows/ci-yocto-weekly.yml
Encountering a problem in calculating long latency tests, we reduce the number of iterations until the problem is solved.
> ci-yocto-weelly: reduce iteration loop

- ansible-requirements.yaml
- prepare.sh
* bump corosync-ansible version
* update roles and collections, even if there are already installed to an outdated version
> Ansible requirements update

- .cqfd/docker/Dockerfile
- playbooks/ci_all_machines_tests.yaml
- scripts/gen_cyclic_test.sh
- scripts/run_cyclictest.py
Add cyclic testing during the
CI tests.
> openlab: add cyclic tests

- inventories/README.md
- inventories/netplan_admin_br0_example.yaml.j2
- inventories/netplan_cluster_example.yaml.j2
- inventories/netplan_ptp_interface_example.yaml.j2
- inventories/seapath_cluster_definition_example.yml
- inventories/seapath_demo_cluster_definition_example.yml
- inventories/seapath_standalone_definition_example.yml
- playbooks/cluster_setup_network.yaml
- templates/000-static-ip.network.j2
Integrate netplan to configure
- admin network
- ptp network
- cluster network IP adresses and OVS bridge
The additionnal vxlan bridge cannot be configured with OVS.
The only API change of this PR is the variable `remove_all_networkd_config` renamed to `remove_all_network_config`
> Netplan integration

- playbooks/deploy_vms_cluster.yaml
- playbooks/tasks/deploy_vm.yaml
* disk_copy is true by default
* live_migration is false by default instead of empty string
* vm_file and vm_file_dest are defined in the taks instead of the playbook
> playbooks/tasks/deploy_vm.yaml: change default value

- library/cluster_vm.py
Commit backport from the debian-main branch commit: d698c7362236b3d5f3190600ff8d3cdb30158785
> bump vm_manager: add migration_downtime option

- library/cluster_vm.py
This commit adds a new command to the cluster_vm module to add a Pacemaker remote. This command requires a VM name, a remote name, a remote address and can optionally take a remote port and a remote timeout.
This commit also adds a new command to the cluster_vm module to remove a Pacemaker remote. This command requires a VM name.
> library/cluster_vm: add new commands to add / remove Pacemaker remotes (Yocto)

- inventories/seapath_cluster_definition_example.yml
- inventories/seapath_standalone_definition_example.yml
- roles/debian/hypervisor/tasks/main.yml
introducing custom_tuned_profile_path to allow a custom tuned profile
> Allow tuned custom profile

- library/cluster_vm.py
This commit adds a new command to the cluster_vm module to add a Pacemaker remote. This command requires a VM name, a remote name, a remote address and can optionally take a remote port and a remote timeout.
This commit also adds a new command to the cluster_vm module to remove a Pacemaker remote. This command requires a VM name.
> library/cluster_vm: add new commands to add / remove Pacemaker remotes

- .github/workflows/ansible-lint-debian.yml
- playbooks/test_run_cukinia.yaml
- roles/snmp/tasks/main.yml
Bump Submodules
-----------------------
typo
-----------------------
force lint on debian runner
-----------------------
fix bad condition/jinja2 syntax
it creates a warning otherwise
> bump and quick fixes

- .cqfdrc
Change the cqfd organization to seapath.
> cqfd: change org to seapath

- inventories/seapath_cluster_definition_example.yml
- inventories/seapath_standalone_definition_example.yml
- roles/snmp/tasks/main.yml
This create the snmp v3 user accounts.
API Change : new inventory variable for the snmp v3 user accounts:
```
snmp_accounts:
- name: user1
password: mypassword1
- name: user2
password: mypassword2
- name: user3
password: mypassword3
```
> Add snmp v3 support

- library/cluster_vm.py
Add support for:
- pacemaker_meta
- pacemaker_params
- pacemaker_utilization
- clear_pacemaker_meta
- clear_pacemaker_params
- clear_pacemaker_utilization
- disk_bus
> library/cluster_vm: update to support new vm_manager options

- .github/workflows/ci-debian.yml
- .github/workflows/ci-yocto.yml
- roles/configure_libvirt/handlers/main.yml
- roles/configure_libvirt/tasks/main.yml
- roles/configure_libvirt/templates/libvirtd.conf.j2
- roles/update/README.md
- roles/update/defaults/main.yaml
- roles/update/meta/main.yml
- roles/update/tasks/main.yaml
* Create an update role based on the update_machine_cluster.yaml and update_machine_standalone.yaml of the main branch.
* Try to generate the CI report in any cases.
> Backport main branch changes

- inventories/seapath_vm_definition_example.yml
- templates/vm/guest.xml.j2
Add support for the emulatorpin and direct network interfaces.
Update the inventory example to include the new parameters.
> templates/vm/guest.xml: improve the VM template

- roles/yocto/kernel_params/tasks/main.yaml
Use the dedicated mount_boot.sh script to mount and unmount the boot partition.
> roles/yocto/kernel_params: use mount_boot.sh script

- .github/workflows/ci-debian-weekly.yml
- .github/workflows/ci-debian.yml
- .github/workflows/ci-yocto-weekly.yml
> .github/workflows: correct names

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Backport the template of the previous main branch (now yocto_legacy)
> .github/ISSUE_TEMPLATE

- .cqfd/docker/Dockerfile
- .cqfdrc
The export flavor creates a tarball of the project including the all the file fetch by the prepare.sh script.
> cqfd: add export flavor

- playbooks/cluster_setup_ha.yaml
- playbooks/cluster_setup_users.yaml
- playbooks/seapath_setup_network.yaml
- playbooks/seapath_setup_timemaster.yaml
This makes it possible to run each playbook individually.
> playbooks: add detect_seapath_distro

- playbooks/ci_latency_tests.yaml
Fixes required for the Yocto CI following recent update of the VM image
> Fix ci latency yocto

- templates/vm/guest.xml.j2
- templates/vm/ssc600.xml.j2
* templates/vm/guest: define vm_features variable if not present
* templates/vm/ssc600: do not set secure-boot firmware feature
> VM templates fixes

- roles/centos_hypervisor/tasks/main.yml
> CentOS remove docker forced start
