seapath/ansible

README.adoc

Add the following changes:
* typo fix
* in "Use Ansible without cqfd" section add netaddr python3 module installation  prerequisite
* move prepare.sh instruction in a dedicated section: "Additional components"

Doc minor changes

---

ansible-requirements.yaml

The **roles:** section header was missing. This header must be present if you mix roles and collections in the same Ansible galaxy requirements file.

ansible-requirements.yaml: fix a syntax error

---

playbooks/ci_deploy_vms.yaml

The MAC address has been added in the Ansible inventories. Take MAC addresses from it instead of using a hard-coded version.

playbooks/ci_deploy_vms: use MAC addresses from Ansible inventories

---

.cqfd/docker/Dockerfile

To avoid an issue during sphinx installation, force the installation of docutils version 0.16.

cqfd: force the version of docutils to 0.16

---

playbooks/ci_boot_machine_from_pxe.yaml
playbooks/ci_enable_vms_dhcp.yaml
playbooks/tasks/deploy_vm_from_template.yaml
templates/dhcp_vms_extra_config.conf.j2
templates/pxe_extra_config.conf.j2

Add the playbook "ci_enable_vms_dhcp.yaml" which starts a DHCP server to give an IP address to the VMs, using the new "pxe" container found in the "containers" repository.
Add the playbook "ci_boot_machine_from_pxe.yaml" to boot machine from  PXE using the new "pxe" container found in the "containers" repository.
With those playbooks, all the container configuration is done in playbooks, including the MAC address and the IP address link.

playbooks: add playbooks to run PXE and DHCP server with the "pxe" container

---

module_documentation_sources/requirements.txt

Do no use Ansible 2.9.0 but the latest Ansible version in 2.9 branches.

module_documentation_sources/requirements.txt: use latest Ansible 2.9

---

src/ceph-ansible-patches/osd_no_package.diff

Ceph-ansible tries to install the parted command with a package manager.
In SEAPATH we do not have package manager and parted is already installed, so ceph-ansible parted installation step failed.
To avoid this failure, we have appended "Seapath Yocto distribtion" to the distribtion list which is used to bypass the parted installation step.
Due to the SEAPAH Yocto distro refactoring the distribution is now not constant, and so the distribution list can no longer be used.
To avoid a failure on this step we now just remove this step.

ceph-ansible-patches: do not check for distribution

---

playbooks/cluster_setup_network.yaml

To avoid the system thinking "rbd" is the official hostname of the host.

rbd hosts last

---

ansible.cfg

Adding ceph-ansible roles in roles path allow using ceph-ansible's playbooks in infrastructure-playbooks directory from the SEAPATH ansible root repository.
infrastructure-playbook directory contains useful playbooks to perform maintenance operation on a Ceph cluster.

ansible.cfg: add ceph-ansible roles directory in roles path

---

playbooks/ci_restart_machines.yaml

Do not reboot if the Ansible variable skip_reboot is defined.

playbooks/ci_restart_machines: support reboot skip

---

scripts/eg_pms2_lan_driver_power.sh

Logout after connecting to the Energenie PMS2 power LAN interface to avoid locking the plug.

scripts/eg_pms2_lan_driver_power: add logout

---

playbooks/replace_machine_remove_machine_from_cluster.yaml
playbooks/replace_machine_shrink_mon.yaml
playbooks/replace_machine_shrink_osd.yaml

Try to detect if the machine where we want to remove a Ceph component is offline.
Avoid running a Ceph action on an offline machine.

playbook/replace_machine_shrink: detect offline machine

---

playbooks/ci_realtime_tests.yaml

Before running RT tests, disable RT-Throttling (give all the CPU time for RT process).
Without disabling RT-Throttling in our setup, the VM will be throttling for 50 ms every second.

playbooks/ci_realtime_tests: disable RT-Throttling for RT tests

---

templates/ovs_configuration.json.j2

The configuration file used by the python3 module setup-ovs and generated by Ansible must be updated to follow changes in setup-ovs.

templates/ovs_configuration.json.j2: update to follow setup-ovs changes

---

playbooks/cluster_setup_keys.yaml

when crm initiates a live migration, the ssh connection between the
source and the destination host goes from the root account on the source
host to the "migration_user" (in our case "virtu") in the destination
host.
This change modifies the source account from virtu to root.

keys playbook: change source user from virtu to root

---

src/debian/consolevm.sh

Since the keys playbook allows root to connect the the other machines
with the virtu user, this changes the behavior of consolevm.sh so that
it also uses virtu as the user for its outgoing connection.

[debian] consolevm: changes user from root to virtu

---

playbooks/cluster_setup_prerequisdebian.yaml
src/debian/80-wired.network

Yocto systemd recipe adds a networkd configuration to enable all
interfaces by default
(https://git.yoctoproject.org/poky/plain/meta/recipes-core/systemd/systemd-conf/wired.network)
This changes reproduces this behavior on debian

[debian] networkd: link up for all interfaces

---

playbooks/cluster_setup_prerequisdebian.yaml
src/debian/corosync_override.conf

it seems that since the team0 interface is created by OVS, its readiness
is not part of the network-online.target.
This changes makes sure corosync wait for team0 (cluster network) to be
up with an IP before starting

[debian] corosync: wait for team0 to be up before starting

---

roles/debian/tasks/main.yml

The base debian image includes a "127.0.0.1 debian" line in the
/etc/hosts file.
This commits make the ansible debian prerequisite role remove it.

[debian] Remove "debian" line from /etc/hosts

---

roles/debian/tasks/main.yml

In the case the playbook needs to change the ip address, the current task has a bug that make the playbook add a new line instead of changing the existing line. This patch solves this.

/etc/hosts: bug when adding the logstash_seapath record

---

templates/syslog-ng.conf.j2

The syslog-ng configuration uses the local time for the messages it
emits. This makes ELK choke (since the default behavior for a logstash
syslog plugin is to consider the timestamp as UTC).
This changes makes syslog-ng uses UTC.

[debian] syslog-ng: make the timestamp UTC

---

playbooks/cluster_setup_elastic.yaml
playbooks/cluster_setup_florentseapath.yaml
roles/debian/tasks/main.yml
src/debian/metricbeat.yml

It seems logstash_seapath is not a valid name according to RFC1035,
since underscore characters are not permitted.
This commit changes the expected name to logstash-seapath.

[debian] change logstash hostname to "logstash-seapath"

---

roles/debian/hypervisor/tasks/main.yml
src/debian/monitor_journalctl.service
src/debian/monitor_journalctl.sh
src/debian/monitor_journalctl_hard.service
src/debian/monitor_journalctl_hard.sh
src/debian/system.conf

When the VMs are stopping/starting/restarting too fast, we encounter a
bug that bricks the host. The console shows logs like:
- "rcu_preempt self-detected stall on CPU"
- "rcuc/5 kthread starved for 5311 jiffies"
- "asm_sysvec_spurious_apic_interrupt"
- "vmx_handle_exit_irqoff"
- etc.
This commit adds some systemd watchdog configuration, plus 2 services
that will monitor the logs for the rcu_preempt message and try to reboot
the host if it does find one.
The first service will try to stop pacemaker cleanly (to migrate the VMs
to other hosts) and then try to reboot the host cleanly.
The second service will just wait 3min and restart the host abruptly, as
a safeguard when the first service is not successful.

[debian] workaround for rcu/kvm bug: reboot host

---

roles/debian/hypervisor/tasks/main.yml

Indeed, GRUB_CMDLINE_LINUX_DEFAULT is set by the seapath iso.

Use GRUB_CMDLINE_LINUX instead of GRUB_CMDLINE_LINUX_DEFAULT

---

.gitmodules

Following PR 15 on vm-manager we can now use the main branch for debian

Use vm_manager main branch

---

.cqfd/docker/check_yaml.sh

The script's output was always 0, even if yamllint found errors in the syntax.
Now, if no error is detected on a file, OK is printed in green next to the file's name.
If an error is detected, KO is printed in red next the file name, the error is printed.
Finally, the total number of errors is printed, and the script exits with 1 if errors were detected.
Signed-off-by: Thibault Sourdin <thibault.sourdin@savoirfairelinux.com>

.cqfd/docker/check_yaml.sh: update script

---

roles/debian/hypervisor/tasks/main.yml
roles/debian/tasks/main.yml

os-prober is call when updating grub (standard thing when updating the kernel or changing the kernel cmdline)
os-prober need the raid6_pq module loaded (via btrfs), this module like to benchmark things at loading and does this with "preempt_disable()" which create huge latencies.
Once the module is loaded, it does not do this benchmarking again.
This patch implements 2 solutions:
- disabling os-prober completely
- pre-loading raid6_pq (just in case something else needs it in the future)

[debian] solving os-prober huge latency

---

playbooks/cluster_setup_network.yaml
templates/ovs_configuration.json.j2

Following https://github.com/seapath/python3-setup-ovs/pull/5, we need ansible to create the cluster network bridges by itself.

Make ansible create the cluster network without setup_open_vswitch

---

vars/network_vars.yml

With a unique ip address, so that VM can join the host they are on using 10.1.1.1

[debian] Adds a local bridge on the hosts

---

roles/debian/hypervisor/tasks/main.yml
src/debian/ptp_docker/compose-ptp_docker.yml
src/debian/ptp_docker/getptpdetails.php
src/debian/ptp_docker/getptpstatus.php
src/debian/ptp_docker/ptpdocker.service
src/debian/ptp_docker/ptpstatus.service
src/debian/ptp_docker/ptpstatus.sh

This webservice will allow the guests to query the host for the current ptp status, which is needed to populate the SmpSync field in a 61850 SV packet.

[debian] Add a host service to provide the PTP status to guests

---

roles/debian/hypervisor/tasks/main.yml

silly typo in the isolcpus kernel boot param

---

roles/debian/hypervisor/tasks/main.yml

According to Redhat, it seems to be a good thing for latency sensitive systems
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_for_real_time/7/html/tuning_guide/reduce_cpu_performance_spikes

Set skew_tick kernel boot param to 1

---

inventories/seapath_cluster_definition_example.yml
playbooks/cluster_setup_ceph.yaml
playbooks/cluster_setup_ha.yaml
playbooks/cluster_setup_keys.yaml
playbooks/cluster_setup_libvirt.yaml
playbooks/cluster_setup_network.yaml
playbooks/cluster_setup_prerequisdebian.yaml

ceph-ansible seems to choke when using "ansible_become". This option forces all playbooks to run as root, but some tasks in ceph-ansible are run locally (delegates_to: localhost) and so require not to run as root (become: false is specifically written for these tasks, but is overriden by ansible_become). For example when running ansible-playbook in doker, this would lead to an "sudo missing" error.
Example: https://github.com/ceph/ceph-ansible/blob/d57377ef619c3304c1eaf4d466dae4055b492d7b/roles/ceph-mon/tasks/deploy_monitors.yml#L27
This patch remove ansible_become from the inventory variables, which will make the playbooks themselves decide if they need to run as root. Therefore this patch also adds the "become: true" option to all playbooks.
Signed-off-by: Florent CARLI …

[debian] stops using ansible_become

---

inventories/seapath_cluster_definition_example.yml
vars/ceph_group_vars/all.yml

ceph-ansible sets the osd memory with space in the var name ("osd memory target")
If we override with a var that has no space ("osd_memory_target"), it creates a duplicate settings...

[debian] osd memory: no space in var

---

.cqfd/docker/Dockerfile
.cqfd/docker/requirements.txt

Rework Python module installation to use pip to avoid a conflict error with Jinja2 module.

cqfd: fix Ansible error

---

.cqfdrc
.gitignore

This flavor exports SEAPATH ansible repository into the ansible.tar.gz archive.

cqfd: add the export flavor

---

inventories/seapath.yaml
playbooks/ci_configure_cluster.yaml
playbooks/cluster_setup_add_virtu_user.yaml

Add the playbook cluster_setup_add_virtu_user.yaml to create the virtu user. This user can be used to perform VM live migration. This playbooks is called during the cluster setup by the ci_configure_cluster.yaml playbook.
By default the virtu user is not created because virtu user have the access rights to manage Pacemaker and libvirt. So if you do not need live migration it is recommended to not enable this feature. To enable it you have to define the Ansible user create_virtu_user.

playbooks: create a user for VM live migration

---

playbooks/ci_set_efi_boot_entries.yaml

The Ansible variable create_efi_entries has to be defined if you want Ansible to create SEAPATH UEFI boot variables.
Note: if you use one of the SEAPATH flash image, SEAPATH UEFI boot variables will be set by it.

playbooks: do not set UEFI boot variables by default

---

playbooks/cluster_setup_network.yaml

Cluster network now use an Open vSwitch bridge, so we also need to configure Open vSwitch for the observer.

playbooks: configure Open vSwitch for observer

---

inventories/seapath_ovstopology_definition_example.yml

Following 36892794e8c585560c662cadf6fdcdfcc5e020bc (Make ansible create the cluster network without setup_open_vswitch), let's update the example OVS inventory file (removing of the team0 bridge details, replaced by the ignored_bridges object).

Team0: Update the example OVS inventory file

---

roles/debian/tasks/main.yml

It is bad practice to override the existing VirtualDomain file since it can/will be overwriten by an upcoming package upgrade. It is recommended to create a custom folder is /usr/lib/ocf/resource.d 
A upcoming PR to bump vm_manager submodule will arrive as soon as the change is merged into vm_manager (https://github.com/seapath/vm_manager/pull/17)

Move seapath VirtualDomain resource agent to custom directory

---

roles/debian/tasks/main.yml

This commit makes the debian prerequisite playbook configure the hddtemp service to expose  hard disks temperature on a standard tcp port, so that it can be easily polled by a supervision system like centreon.

hddtemp: configuring the hard disk temperature monitoring

---

.gitmodules
prepare.sh

Since our submodules are based on branches (main, master...) we need the remote option to force the fetching of latest references from the origins
And since we add this option, we also must make sure all git submodules have a branch to fetch

add the --remote option when updating submodules

---

roles/debian/hypervisor/tasks/main.yml

disables Linux kernel clocksource watchdog (best practice for realtime), as well as the stability checks done at bootup

hypervisors: set tsc=reliable in cmdline

---

roles/debian/tasks/main.yml
src/debian/snmp_cephstatus.sh
src/debian/snmp_cephusage.sh
src/debian/snmpd.conf

This commit allow the ceph status to be exposed with snmpd, so that polling system like nagios are able to retrieve ceph health data

snmp: exposes ceph status

---

roles/debian/tasks/main.yml
src/debian/corosync_override.conf
src/debian/systemd-networkd-wait-online_override.conf

Right now the network-online.target is reached before all needed interfaces are up. This poses a problem for corosync (team0 being not up when corosync starts, it fails), problem we solved with a dirty hack (wait loop in a systemd service override).
We have the same problem with newly added service "hddtemp".
This commit cleans everything up by setting up systemd-networkd-wait-online.service and configuring it to wait for at least interfaces br0 and team0. network-online.target will only be reached once
systemd-networkd-wait-online.service is completed, which will solve both corosync and hddtemp timing problems.

setup up systemd-networkd-wait-online.service to replace dirty corosync hack

---

inventories/seapath_cluster_definition_example.yml
playbooks/cluster_setup_network.yaml
templates/timemaster.conf.j2

Right now we are using systemd-timesyncd for basic NTP configuration. This commit replaces systemd-timesyncd by timemaster and allow either to use PTP with NTP backup or directly NTP.
The PTP configuration must be done in the inventory with the definition of the "ptp_interface" for each host.
The NTP configuration is done in the inventory with the ntp_primary_server and ntp_seconday_server variables

Timemaster: allow PTP configuration for hosts

---

playbooks/cluster_setup_network.yaml
roles/debian/tasks/main.yml
src/debian/systemd-networkd-wait-online_override.conf
templates/systemd-networkd-wait-online.service.j2

Commit 48709fc added some networkd wait logic to the debian role (waiting for br0 + team0 interfaces), but there actually already was some networkd logic in the networking playbook.
This commit merges both in the networking playbook.

Move networkd wait stuff from debian role to network playbook

---

roles/debian/tasks/main.yml

This is necessary in case the user delegates the users/groups/sudo management to an external directory (ldap, activedirectory...) : the directory imposes the uid/gid and so we need to set the same so that there is a local backup with the same uid/gid.
This is true for specific service accounts which right now are:
- virtu (uid/gid=1000), set by build_debian_iso
- ansible (uid/gid=1005), set by build_debian_iso
- ceph (uid/gid=64045), set by ceph installation package
- Debian-snmp (uid/gid=10002), set by the ansible playbook (object of this commit)
Other accounts have no point being managed by an external directory

Fixing the uid/gid of the Debian-snmp account

---

playbooks/cluster_setup_network.yaml

0d5f3e83a906880eb90fb9a98cfbce704e5e0198 make the network playbook restart timemaster even when there is no change.
This commit fixes this.

Silly bug in Timemaster playbook

---

roles/debian/hypervisor/tasks/main.yml
roles/debian/tasks/main.yml

The RT sysctl settings should go in the debian/hypervisor role, whereas the non RT specific sysctl settings should stay in the debian role.

debian roles: split sysctl settings (rt and non rt)

---

playbooks/cluster_setup_network.yaml

The debian iso comes with default networking. This commit makes sure this default is removed when we apply the target network configuration.

Remove default FAI-networking

---

.gitignore
playbooks/standalone_rt.yaml

Playbook to deploy only the RT requirements on a debian machine without any cluster features

new playbook for rt only requirements

---

roles/debian/tasks/main.yml
src/debian/00-bridge_nf_call.conf

https://unix.stackexchange.com/questions/572022/linux-bridge-for-virtual-machines-not-forwarding-ip-packets-but-is-forwarding-a
This had already been added with commit d8abc1f and add been removed by c4514f4. When I rollback the changed of c4514f4 in commit 0e9b0ab, I forgot to reapply this needed workaround.

rules for trafic to reach the VM from outside

---

playbooks/ci_restore_snapshot.yaml
playbooks/ci_the_one_playbook.yaml

Use LVM to rollback to the initial state before running the CI.

playbooks: rollback before running the CI

---

prepare.sh

The --remote option checkouts the submodule to the latest remote
tracking branch revision instead of the specified SHA1 commit.
This doesn't allow to test the submodules through the CI since the
commits to be verified are not yet merged.

Submodule ci

---

playbooks/ci_configure.yaml
playbooks/ci_restore_snapshot.yaml
playbooks/cluster_setup_debian.yaml
playbooks/cluster_setup_network.yaml
roles/debian-hardening/handlers/main.yml
roles/debian-hardening/tasks/main.yml

To ensure all changes are applied reboot at the end of the debian-hardening role.

roles/debian-hardening: force reboot after applying the role

---

.gitignore
playbooks/vm_deploy.yaml
playbooks/vm_remove.yaml
templates/vm/votp_vm_standard_config.xml.j2
vm_images/README

This PR adds following files:
Playbooks:
- `vm_deploy.yaml`: a playbook to create and start a VM in cluster. VM image source file must be put in `vm_images/` directory.  The VM is identified by an unique id set by `vm_id` variable. VM image source file must be set using `image_name` variable.
- `vm_remove.yaml`: a playbook to stop and remove a VM in cluster. The VM is identified by an unique id set by `vm_id` variable.
Configuration templates: 
- `votp_vm_standard_config.xml.j2`: a standard configuration based on `votp_vm_rt_isolated.xml.j2` but using 1Gb of RAM.

Add playbooks to deploy VM's 

---

roles/debian/hypervisor/tasks/main.yml

Create 5 virtual NIC using SR-IOV on Intel NIC which use the IGB driver.

roles/debian/hypervisor: enable SR-IOV for IGB

---

.gitignore
playbooks/test_run_latency_tests.yaml
src/svtools/README
src/trafgen/README
tests_results/README

This PR adds modification needed to run latency tests on cluster.
Following files and directories are added:
- `playbooks/test_run_latency_tests.yaml`: a playbook to run latency test in the cluster, using a dedicated publisher machine, and successively hypervisor and VM as subscriber machine. 
**Caution:** To deploy publisher tests, you will need a dedicated machine hosted as `standalone` in your inventory.
- `src/trafgen/` and `src/svtools`: source directories for publisher and subscriber source code.
- `tests_results/`: data results of publisher and subscriber tests directory.

Latency tests deployment

---

inventories/seapath_standalone_definition_example.yml
playbooks/cluster_setup_network.yaml
playbooks/cluster_setup_prerequisdebian.yaml
vars/network_vars.yml

This commit allow a standalone node to be deployed with both playbooks cluster_setup_prerequisdebian.yaml and cluster_setup_network.yaml The inventory needs to be different, and define a "standalone_machine" object instead of a "cluster_machines" object.

Standalone mode: allow the playbooks to deploy a single node

---

playbooks/test_deploy_cukinia_tests.yaml
roles/debian-hardening/tasks/main.yml
src/debian/auditd/audit.rules
src/debian/auditd/syslog.conf

This PR adds a playbook  `playbooks/cluster_setup_auditd.yaml` to properly configure auditd on target:
- Redirect all auditd output to syslog
- Configure auditd rules
- Python scripts to generate syscall needed by Cukinia to test auditd rules

Anssi bp 028 r73

---

playbooks/cluster_setup_network.yaml
templates/ovs_configuration.json.j2

Standalone mode needs OVS configuration
However standalone mode does not have team0 (cluster network) and so does not need the ignored_bridges object.

Standalone mode: missing bits

---

playbooks/cluster_setup_network.yaml
templates/timemaster.conf.j2
templates/timemaster.service.j2

Timemaster may start too soon, before networking is ready, in which case the synchronization never starts. This commit fixes that.

[debian] timemaster: add dependency on networking

---

playbooks/test_deploy_cukinia_tests.yaml

sources.list can now be configured to use an apt proxy instead of official repositories.
SFL: #9314
Change-Id: Ibc5ef5f90cce78d27f35d515611ee9c6dc3fcf9f

cukinia_tests: use template for apt.conf

---

src/debian/backup-restore/restore_vm.sh

An evolution in vm-manager makes is necessary to fix backup-restore.sh (live migration options syntax)

Bump submodules + adapt backup-restore script

---

playbooks/cluster_setup_prerequisdebian.yaml
roles/debian/tasks/main.yml

Host UUID is read from one of the sources specified in host_uuid_source.
- 'smbios': fetch the UUID from 'dmidecode -s system-uuid'
- 'machine-id': fetch the UUID from /etc/machine-id
By default, smbios is used. We found that it did not give unique results for some hardware vendors (Moxa, Advantech)
machine-id works better to have unique UUID for hosts.

make libvirt use the machine-id way of determining host UUID

---

roles/debian/hypervisor/tasks/main.yml
roles/debian/tasks/main.yml

Previously, ipv6 was disabled in the hypervisor playbook. The observer still had ipv6 enabled. This commit makes the ipv6 disabling happen in the debian (all nodes) playbook.

[debian] Disable IPV6 for all machines (not just hypervisors)

---

inventories/seapath_cluster_definition_example.yml
src/debian/snmpd.conf.j2

Currently br0 is created for "remote access" to the hosts, with the "ansible_host" ip address. Users may need to have snmpd (or other services) listen to a different ip address.
This commit introduces "admin_ip_address", a variable for the ip address used for administrative services (right now only snmpd).

[debian] Introducing ip address for administration

---

roles/debian/tasks/main.yml
src/debian/backup-restore/backup-restore.sh
src/debian/backup-restore/edit_metadata.sh
src/debian/backup-restore/restore_vm.sh

Since these scripts are not part of the debian distribution, they should be stored in /usr/local

[debian] Move custom scripts from /usr/bin to /usr/local/bin

---

src/debian/VirtualDomain

When force stopping a guest, Pacemaker only gives 5s to libvirt to destroy the VM.
Libvirt gives itself 10s before the original SIGTERM and the final SIGKILL, so a guest can take up to 11-12 seconds to be destroyed. This commit make the VirtualDomain Resource agent give 12s to libvirt.

Increase shutdown timeout to 12s

---

roles/debian/tasks/main.yml
src/debian/snmpd.conf.j2
src/debian/sudoers/Debian-snmp

Debian-snmp uses sudo to execute privileged command, it does not need to be in the haclient and libvirt group

Remove Debian-snmp from haclient and libvirt group

---

.github/workflows/ci-debian.yml

A new runner for the yocto version of SEAPATH will soon be added. A tag will be used to differentiate the two runner.
This commit add the tag "runner-RTE" to the workflow for the debian CI.

.github/workflows: add label for RTE runner

---

ansible-lint.conf
playbooks/test_deploy_cukinia.yaml
roles/debian-hardening/tasks/main.yml

The rule "no-tabs" was skipped because a playbook needed to be refactor. This is done now and the rule should not be skipped anymore.

ansible-lint.conf: remove no-tabs exclusion

---

.github/workflows/ansible-lint-weekly.yml
.github/workflows/ci-yocto-weekly.yml

The last badges were not created properly. Change the schedule time to re-generate them.

workflows: change schedule time to create badges

---

.github/workflows/ansible-lint-weekly.yml
.github/workflows/ci-yocto-weekly.yml

In order to display all badges the same way on the seapath github main page, the weekly workflows have to be renamed.
A weekly CI for debian should also be created and all workflows correctly named after that.

workflows: rename weekly badges

---

playbooks/cluster_setup_libvirt.yaml

var | length > 0 for var != ""
car | length == 0 for var == ""

playbooks/cluster_setup_libvirt: fix empty string comparison

---

playbooks/cluster_setup_network.yaml

With the changing in build_debian_iso we have to remove 01-init.network and 00-init-dhcp.network.

playbooks/cluster_setup_network: update removing FAI network files

---

roles/debian/hypervisor/tasks/main.yml
roles/debian/tasks/main.yml

Following https://github.com/seapath/build_debian_iso/pull/57 FAI now has multiple default files for grub
Ansible needs to remove all of them, hence the use of a wildcard pattern (we remove all files in /etc/default/grub.d starting with 2 digits and ending in .cfg)

debian prereq: remove all FAI grub defaults

---

playbooks/ci_cleanup_syslog.yaml
playbooks/ci_restore_snapshot.yaml
playbooks/cluster_setup_hardened_debian.yaml
playbooks/test_deploy_cukinia.yaml
playbooks/test_deploy_cukinia_tests.yaml
playbooks/test_run_cukinia.yaml

ansible_become overrides all playbooks, including externally developped (like ceph-ansible).
It's better practice to use "become" on a playbook to playbook basis.

Removing "ansible_become" of inventory

---

examples/inventories/vms_inventory_example.yaml
playbooks/deploy_vms_cluster.yaml
playbooks/deploy_vms_standalone.yaml

The Ansible VM variable pinned_host and preferred_host can now be used to choose when the VM will be deploy and if the VM will migrate or not.

playbooks/deploy_vms_cluster: add support for pinned and preferred host

---

templates/timemaster.service.j2

Prevent a race condition which could make timemaster fail because the virtual ptp interface was not ready.

Redoing commit c82f3f1 with variabilized interface

---

templates/timemaster.conf.j2

In case of a link down event on the ptp interface, the PHC is reset and without this option, ptp4l takes forever to compensate for the 37s (TAI-UTC) offset.

timemaster: add step_threshold option to ptp4l

---

templates/timemaster.service.j2

Following c16e5b559a2bfc466ce0d09de41f1ccabbcfff12, it seems that on debian 11, the physical interface on systemd is called sys-subsystem-net-devices-X and not sys-devices-virtual-net-X

timemaster.service: change in ptp device dependency

---

src/debian/backup-restore/restore_vm.sh

The current wildcard may rsync files that do not concern the guest we are trying to restore

restore_vm.sh: more precise wildcard

---

roles/debian/tasks/main.yml

10002 is not a system uid (<=999) and so this breaks any snmpd upgrade.
having a uid<1000 will solve this

snmpd: change debian-snmp user uid to 902

---

inventories/seapath_cluster_definition_example.yml
templates/timemaster.conf.j2

Replacing ntp_primary_server and ntp_secondary_server variables with ntp_servers which is an array (not limited to 2 items). 
The first item will be the preferred server if no ptp interface is defined. 
For now the change is retro-compatible.

ntp: allow more than 2 NTP servers

---

inventories/seapath_cluster_definition_example.yml
inventories/seapath_standalone_definition_example.yml
playbooks/cluster_setup_keys.yaml
playbooks/test_deploy_cukinia_tests.yaml
roles/debian-hardening/tasks/main.yml
roles/debian/tasks/main.yml
src/debian/consolevm.sh.j2
src/debian/sudoers/virtu

Following #225, this PR will variabilize the current "virtu" user (with the "admin_user" variable) and add a user dedicated for libvirt live-migration (in "livemigration_user" variable).
If the "admin_user" is different than "virtu", then the playbook will remove the useless virtu user.
Note that the "admin_user" account will need a password (Seapath CI testing does not allow this user to be password-locked), hence the "admin_password" var to define the password hash.
ssh public keys can also be set for this user with the admin_ssh_keys variable

split and variabilize accounts used for rescue access and libvirt live-migration

---

inventories/seapath_cluster_definition_example.yml

same fix as in a608f84671aabf38a4444360c00ea8097c6c8125
ceph-ansible sets the osd memory with space in the var name ("osd memory target")
If we override with a var that has no space ("osd_memory_target"), it creates a duplicate setting...

inventory: osd memory target example

---

playbooks/cluster_setup_keys.yaml

This is needed for "consolevm" script to work since it connects from one host to another using ssh and the admin_user user.

keys: add root ssh key to admin user

---

inventories/seapath_cluster_definition_example.yml

This is required by the hardening playbook which looks for the "lnk_source" to create the sudo rule
But anyway it's still a best practice since the scsi disk order may vary depending on the hardware

inventory: impose ceph_osd_disk to use the /dev/disk/by-path

---

playbooks/cluster_setup_ceph.yaml

Sometimes the zap process fails because the ceph vg and lv are not completely gone:
----
fatal: [virtu-ci3]: FAILED! => changed=true
cmd:
- ceph-volume
- lvm
- zap
- /dev/sda
- --destroy delta: '0:00:41.390807' end: '2023-07-12 11:34:42.307674' msg: non-zero return code rc: 1 start: '2023-07-12 11:34:00.916867' stderr: |- --> Zapping: /dev/sda --> Zapping lvm member /dev/sda. lv_path is /dev/vg_ceph/lv_ceph stderr: Unknown device "/dev/vg_ceph/lv_ceph": No such file or directory stderr: wipefs: error: /dev/vg_ceph/lv_ceph: probing initialization failed: No such file or directory ----

ceph: force lvm vg refresh before zapping and creating the ceph vg/lv

---

templates/vm/seapath_guest_nort.xml.j2
templates/vm/seapath_guest_rt.xml.j2

Cleaning VM NORT and RT templates.
Libvirt automatically creates the following information, which has now been removed:
- currentMemory unit
- emulator
- controller type
Additionally, unnecessary information within the interface configuration has been removed:
- alias name
Added rng device in all basis templates.
Also added emulatorpin option in cputune.

Cleaning VM NORT and RT templates

---

ansible.cfg
playbooks/cluster_setup_ceph.yaml
roles/debian/tasks/main.yml
src/debian/lvm_snapshot_rebooter.sh

This change has to be merged ASAP for the CI to be functionnal.
A CI workflow on a "lvm rebooter" PR crashed the initramfs so I had to reinstall the 3 servers. I used a software raid installation for which the ceph VG and LV are created with the ISO. We need to make a change in the ceph playbook for this case to be dealt with.
Indeed, it might be a good target to assume the ceph VG and LV have already been created (for example for a softraid situation). In that case the ceph playbook must deal with multiple possibilities:
- Is it a new ceph installation or not ?
- if it's a new installation, do we already have the ceph VG and LV, in which case we zap them and move to the installation
- if the ceph VG and LV don't exist, are we really in a "customized lvm situation"
- if we are, then we …

Fix CI: ceph VG/LG already exist + introducing lvm_snapshot_rebooter

---

inventories/seapath_cluster_definition_example.yml
library/cluster_vm.py
playbooks/cluster_setup_ha.yaml
playbooks/deploy_vms_cluster.yaml
playbooks/tasks/deploy_vm.yaml

This will allow running custom "crm configure" commands at the end of the HA playbook. This can allow setup location resources for guests (ping or else), stickiness parameters or even fencing options.
Then we need to allow the guests to embed customize location rules, and for that we make the necessary adjustement to the vm-manager ansible plugin. 
The needed improvement has been done in vm_manager with commit https://github.com/seapath/vm_manager/commit/9701165b7f464a1beb7e79316234e999081fc9e1

run extra crm commands

---

library/cluster_vm.py
playbooks/deploy_vms_cluster.yaml
playbooks/tasks/deploy_vm.yaml

If crm_config_cmd is not defined for a VM, it is created empty by vm-mgr and that causes problems.
This patch makes sure crm_config_cmd is not created when not present in the VM definition

deploy_vm: absence of crm_config_cmd bug

---

inventories/seapath_cluster_definition_example.yml
playbooks/cluster_setup_network.yaml
roles/debian/physical_machine/tasks/main.yml
src/debian/chrony-wait.service.j2
src/debian/hsr.service
src/debian/hsr.sh.j2
src/debian/hsrstop.sh.j2
src/debian/pacemaker_override.conf.j2
templates/00-GUESTtap.netdev.j2
templates/00-GUESTtap.network.j2
templates/ovs_configuration.json.j2
templates/systemd-networkd-wait-online.service.j2
vars/network_vars.yml

**example inventory: cleanup + add SR-IOV example**
----
**add support for vlan on br0**
Seapath configures the main network interface of the host in a bridge called br0. This is to allow a Guest to easily bridge on this interface, to give that guest easy remote access. 
In some network topologies, this main host network interface is a trunk, and the host need to support vlan tagging to get access to the network. 
This commit makes this topology supported, throught the use of the "br0vlan" configuration variable (in which the user simply has to set the vlanid number).
Then we have to provide a way to configure the guests access to br0. 
This is now possible with the "guest_on_br0" variable in which we define the tap interfaces for the guests (port access or trunk are possible). The user …

waiting changes

---

.cqfd/docker/Dockerfile
.github/workflows/ci-debian.yml
.gitmodules
README.adoc
inventories/seapath_cluster_definition_example.yml
inventories/seapath_standalone_definition_example.yml
prepare.sh
roles/debian-hardening/physical_machine/tasks/main.yml
src/debian/ceph-crash_hardening.conf
src/debian/sudoers/ceph.j2

In accordance with SEAPATH TSC on Oct 12, 2023, this PR will make ansible compatible with deploying seapath on blank nodes running debian 12.
The branch "debian11" has been created based on current debian-main.

Changes needed to upgrade to Debian 12

---

library/cluster_vm.py
src/debian/pacemaker_ra/VirtualDomain

When we stop 2 nodes, the remaining node is not supposed to run any guest. In our current setup, that means the remaining node will try to gracefully stop the running nodes it has. But the problem is that ceph is not available anymore if 2 nodes are missing, so the disks of the guests are not available. Gracefully shutting the vm will not be possible + we noticed some non-reliable behavior when the storage layer is missing. In some cases, "virsh shutdown" will take 30s to a minute to return, which is not compatible with the pacemaker resource agent (pacemaker will timeout after 25sec, so the virsh destroy will not have been sent...). For this problem, this commit makes the pacemaker VirtualDomain RA timeout the "virsh shutdown" command after 1 sec. If the timeout has been reached, then we …

VirtualDomain RA: deal with 2 nodes down (backport)

---

library/cluster_vm.py
src/debian/pacemaker_ra/VirtualDomain

When we stop 2 nodes, the remaining node is not supposed to run any guest. In our current setup, that means the remaining node will try to gracefully stop the running nodes it has. But the problem is that ceph is not available anymore if 2 nodes are missing, so the disks of the guests are not available. Gracefully shutting the vm will not be possible + we noticed some non-reliable behavior when the storage layer is missing. In some cases, "virsh shutdown" will take 30s to a minute to return, which is not compatible with the pacemaker resource agent (pacemaker will timeout after 25sec, so the virsh destroy will not have been sent...). For this problem, this commit makes the pacemaker VirtualDomain RA timeout the "virsh shutdown" command after 1 sec. If the timeout has been reached, then we …

VirtualDomain RA: deal with 2 nodes down

---

roles/debian/physical_machine/tasks/main.yml
src/debian/virt-df.sh

virt-df.sh makes it possible for the hypervisors to retrieve the disk occupation of the guests (by mounting the rbd readonly). This commits adds compatibility for lvm on guests.

virt-df.sh: adds lvm compatibility

---

roles/debian/physical_machine/tasks/main.yml
src/debian/virt-df.sh

virt-df.sh makes it possible for the hypervisors to retrieve the disk occupation of the guests (by mounting the rbd readonly). This commits adds compatibility for lvm on guests.

virt-df.sh: adds lvm compatibility (backport debian11)

---

yocto_standalone_ci.adoc

The documentation described how to setup a machine to be used as the Yocto standalone CI hypervisor and how to keep updating this machine.

doc: create a Yocto standalone CI setup documentation

---

playbooks/ci_all_machines_tests.yaml

The playbook will run all tests defined in /etc/cukinia/cukinia.conf.

playbooks: add a playbook to run all Cukinia's tests

---

inventories/seapath_cluster_definition_example.yml
playbooks/cluster_setup_ha.yaml
roles/debian/physical_machine/tasks/main.yml
src/debian/pacemaker_hardening.conf
src/debian/vmmgrapi/gunicorn.service
src/debian/vmmgrapi/gunicorn.socket
src/debian/vmmgrapi/nginx.conf.j2
src/debian/vmmgrapi/wsgi.py

adds vm_manager flask REST api
vm_manager provides a basic flask REST api.
This commit configures SEAPATH to securely expose this API (can be enabled/disabled in the inventory).
Since the API is python based, we use nginx and gunicorn (which will need to be installed on the hosts, along with python3-flask and python3-flaskext.wtf used for CSRF protection)..
- All node will have a gunicorn systemd socket running
- This socket will belong to www-data with chmod 600 (/run/gunicorn.sock) : only the www-data user (nginx) can use the API. Not even a local user can use it.
- This socket is bound to the gunicorn service, exposing the vm_mgr api. This service will only be launched when needed.
- nginx will be used to expose the gunicorn socket
- nginx will be managed by pacemaker as a systemd …

adds vm_manager flask REST api

---

inventories/seapath_cluster_definition_example.yml
playbooks/cluster_setup_ha.yaml
roles/debian/physical_machine/tasks/main.yml
src/debian/pacemaker_hardening.conf
src/debian/vmmgrapi/gunicorn.service
src/debian/vmmgrapi/gunicorn.socket
src/debian/vmmgrapi/nginx.conf.j2
src/debian/vmmgrapi/wsgi.py

vm_manager provides a basic flask REST api.
This commit configures SEAPATH to securely expose this API (can be enabled/disabled in the inventory). Since the API is python based, we use nginx and gunicorn (which will need to be installed on the hosts, along with python3-flask and python3-flaskext.wtf used for CSRF protection)..
- All node will have a gunicorn systemd socket running
- This socket will belong to www-data with chmod 600 (/run/gunicorn.sock) : only the www-data user (nginx) can use the API. Not even a local user can use it.
- This socket is bound to the gunicorn service, exposing the vm_mgr api with WSGI. This service will only be launched when needed.
- nginx will be used to expose the gunicorn socket
- nginx will be managed by pacemaker as a systemd resource
- this resource …

adds vm_manager flask REST api (backport debian11)

---

playbooks/ci_restore_snapshot.yaml
roles/debian/physical_machine/tasks/main.yml

When the flask api is disabled in the inventory, the playbook makes sure the gunicorn socket is stopped.
This commit makes sure the gunicorn socket exists before we try to disable/stop it.
Also this commit makes sure the gunicorn.service unit is disabled.

FlaskAPI: fix bug gunicorn

---

playbooks/ci_restore_snapshot.yaml
roles/debian/physical_machine/tasks/main.yml

[Bump Submodules](https://github.com/seapath/ansible/commit/2f21459d08202f4c8a15d35114fa800ae2640071)
----
[FlaskAPI: fix bug gunicorn](https://github.com/seapath/ansible/commit/ca17f94e031894eb4160413ebad9c02835ead98d)
When the flask api is disabled in the inventory, the playbook makes sure the gunicorn socket is stopped.
This commit makes sure the gunicorn socket exists before we try to disable/stop it.
Also this commit makes sure the gunicorn.service unit is disabled.
----
[ci snapshot: create a snapshot as big as the LV](https://github.com/seapath/ansible/commit/8a238a410b60097201790145fe40a282a5064268)
So that the snapshot can't become invalid with time

Backport debian11 202311221129

---

roles/debian/hypervisor/tasks/main.yml

This commit makes it possible to change a value of a grub cmdline parameter. 
Before this commit "key=value1" and "key=value2" were considered as two different token, and so changing from value1 to value2 would just add "key=value2" over "key=value1".
This commit changed the regexp so that changing an existing key is possible..
This commit also removes hugepagesz=1G and no_debug_objects which are not useful for now.

hypervisor role: solved grub task bug

---

roles/debian/tasks/main.yml

On industrial servers, we can assume the fsck repair needs to be done automatically if it ever needs to be done. 
See https://askubuntu.com/questions/1006417/automatically-force-fsck-fy-when-encountering-unexpected-inconsistency-run-fs

debian role: add automatic mode to forced boot fsck

---

playbooks/cluster_setup_network.yaml

Networking: change mac address of internal team0 interface
By default the team0 internal interface will have the same mac address as one of the physical interfaces.
This becomes a problem when using udev/networkd to customize the physical interface based on its mac address.
The internal interface needs its own mac address, that we can generate randomly.
----
Networking playbook: allow ovs-vsctl extra commands
Since votp-config_ovs destroys and recreate the whole OVS topology at every start, we need a way to persist specifities in the bridges configuration (for example: NetFlows exporters...). We introduce the inventory variable "ovs_vsctl_cmds" for this purpose.

Multiple networking changes

---

inventories/seapath_cluster_definition_example.yml
roles/debian/hypervisor/tasks/main.yml

IRQBALANCE_BANNED_CPUS is discarded in debian 12

irqbalance: use IRQBALANCE_BANNED_CPULIST

---

OVS_configuration.adoc
inventories/seapath_cluster_definition_example.yml
inventories/seapath_standalone_definition_example.yml

The setup_ovs module allows the seapath user to use openflow rules to enable/disable ipv6 between guests, and to do antispoofing (based on mac/ip addresses of guests). There is currently no way to do more than that.
This commits allows the user to override the openflow table with custom rules, using the "flows_override" inventory variable.

openflow: provides a way to override the whole flow tables

---

vars/network_vars.yml

In case of VLAN filtering, we let the physical port accept ALL vlan ids by defau
lts (1-4094)

network_vars: remove vlan filtering on physical port

---

inventories/seapath_cluster_definition_example.yml
inventories/seapath_standalone_definition_example.yml

On debian 12, irqmask is replaced with isolcpus in /etc/default/irqbalance

inventories fixes for irqbalance on debian12

---

src/debian/virt-df.sh

Otherwise, df will try to query the EFIvars which can cause unwanted kernel latencies

virt-df.sh: reduce df scope to /t

---

.github/workflows/ci-debian.yml

A submodule was added in the CI repository to get test-report-pdf. This commit adds the fetch of this submodule when cloning the CI in the GitHub Action file.

workflows/ci-debian: clone with submodules

---

playbooks/cluster_setup_network.yaml

Changing the mac address of the br0 default internal interface does not do anything, since the task just after (RSTP setting), makes the macaddress change back to default. This change was introduced in the first place to that we could use udev (.link files in networkd) to rename physical interfaces based on their macaddress.
Since the br0 internal interface gets the same address as one physical interface in the bridge, udev tried to rename the ovs internal interface as well... and hanged. The workaround is to specify "Kind=!openvswitch" in the Match section of the link file.

network playbook: do not change the macaddress of br0

---

inventories/seapath_cluster_definition_example.yml
playbooks/cluster_setup_ha.yaml

the extra cmd to run with crm are run every time the playbook is run, with errors being ignored
This is kind of declarative and idempotent but:
1) it does not support modification of existing resources (if the resource exists, it will just fail, not modify it)
2) it runs a cmd task for every line/resource
3) it does not return whether something was actually changed or not
4) it requires failures to be ignored
All in all, it's not very clean.
With this commit all this problems are solved.
1) the "crm load update" process will update an existing resource and create it if it does not exist
2) it runs only once for all resources
3) we use "changed_when" to find out if something was actually changed
4) we still have full logging and failure detection if needs be

ha playbook: improves the extra cmd to run

---

src/debian/backup-restore/backup-restore.sh
src/debian/backup-restore/backup_du.py
src/debian/backup-restore/backup_full.sh
src/debian/backup-restore/backup_inc.sh

It might be useful for an administrators to more precisely select the Guests that needs backuping.
This commit introduces the include_vm and exclude_vm settings in backup-restore.sh, and a feature to estimate the associated needed storage.

backup-restore: include/exclude VM options and estimated storage

---

examples/playbooks/add_vm_playbook_example.yaml

The vm_template_example.xml.j2 template file added on this playbook is now in the ./examples/vm_templates path. Thus, the old path is replace is in this commit.

add_vm_playbook_example: fix path of vm_template

---

README.adoc

Typo on the word children in the Inventory section.

README.adoc: correct typo

---

inventories/seapath_cluster_definition_example.yml
inventories/seapath_standalone_definition_example.yml
roles/debian-hardening/physical_machine/tasks/main.yml
roles/debian/physical_machine/tasks/main.yml
src/debian/snmpd.conf.j2

When the snmp administration ip is not provided, snmp is not configured on the host.

Make snmp optional

---

examples/inventories/advanced_inventory_cluster_example.yaml
playbooks/cluster_setup_network.yaml

The variable `syslog_server_ip` is now optional. When not given, no logs will be sent.

cluster_setup_network: make syslog optional

---

inventories/seapath_cluster_definition_example.yml
inventories/seapath_standalone_definition_example.yml
playbooks/cluster_setup_configure_nic_irq_affinity.yaml
playbooks/tasks/setup_nic_irq_affinity.yaml
src/setup_nic_irq_affinity.py
src/setup_nic_irq_affinity.service
templates/setup_nic_irq_affinity.j2

This playbook is used to configure the NICs IRQs affinity to the CPUs. It creates a systemd service that will run a python script to set the IRQs affinity of the NICs to the CPUs.
To use it, add the Ansible variable nics_affinity to the inventory file. For example:
nics_affinity:
- eth0: 0-3,4-7
- eth1: 8-11,12-15

playbooks: Add a playbook to configure NICs IRQs affinity

---

templates/timemaster.conf.j2

Verbosity level 6->4 prevent seeing regulation values once every second (Those can be enabled back locally for debug)

timemaster: Decrease ptp4l verbosity

---

playbooks/cluster_setup_network.yaml
src/ptp4l.conf
src/ptp4l.service.override
vars/network_vars.yml

* Allows the use of any interface for PTP, not only the main interface.
* Add a configure file for ptp4l which respects the IEC 61850-9-3 standard.
* Restart ptp4l and phc2sys services in case there are already started.

PTP refactor

---

.github/workflows/ansible-lint-yocto-weekly.yml

The ansible-lint-yocto-weekly workflow was using the wrong file to execute the ansible-lint action. This commit fixes the issue by using the correct file.

github/workflows: fix ansible-lint-yocto-weekly workflow

---

.github/workflows/ansible-lint-yocto-weekly.yml
.github/workflows/ci-yocto-weekly.yml

This PR adds the workflow_dispatch event to the weekly workflows ansible-lint-yocto-weekly.yml and ci-yocto-weekly.yml. This will allow us to manually trigger the workflows from the GitHub Actions UI.
It also renames the weekly workflows to be more explicit about their purpose.

github/workflows: add workflow_dispatch to weekly workflows

---

.github/workflows/ansible-lint-debian-weekly.yml
.github/workflows/ci-debian-weekly.yml

* Fix the ansible-lint-debian-weekly wrong workflow file.
* Renames the weekly workflows to be more explicit about their purpose.
* Allow to manually trigger weekly workflows from the github interface.

github/workflows: fix ansible-lint-debian-weekly workflow

---

.github/workflows/ansible-lint-debian-weekly.yml
.github/workflows/ci-debian-weekly.yml

This patch adds a weekly CI for the debian-main branch. It will run the system, VM and latency tests and upload the report to the CI server. It also adds a weekly job for the ansible-lint.
Schedule workflows and workflow_dispatch have to be defined in the default branch.

github/workflows: add weekly debian CI

---

.github/workflows/ansible-lint-debian-weekly.yml

The name of the weekly Debian workflow was wrong.

github/workflows: fix Debian weekly name

---

.github/workflows/ci-debian-weekly.yml

The ci-debian-weekly workflow use a custom way to fetch the sources, using the `GITHUB_REF` environment variable to fetch the correct branch.

github/workflows: fix ci-debian-weekly fetch

---

roles/debian-hardening/tasks/main.yml
src/debian/sudoers/cockpit

When hardening is enable, it is not possible to run command outside a tty. This cause Cockpit to not be able to be used with an administrator with the admin privilege.
Disable `require-tty` for command `/usr/bin/cockpit-bridge --privileged` in order to enable administrative access in cockpit, for authorized users.

hardening: disable requiretty for cockpit

---

roles/debian/hypervisor/tasks/main.yml
templates/00-workqueue_cpumask.conf.j2

This commit makes the isolcpus and workqueues configurations optional.
If they were previously set up and and unconfigured later in the inventory, this commit also deals with the revert operations.

Make isolcpus and workqueues optional and revertable

---

inventories/seapath_cluster_definition_example.yml
inventories/seapath_standalone_definition_example.yml
src/debian/chrony-wait.service.j2

Make the variable chrony_wait_timeout_sec optional. Default to 180 seconds

Make chrony wait timeout sec optional

---

inventories/seapath_cluster_definition_example.yml
inventories/seapath_standalone_definition_example.yml
playbooks/cluster_setup_prerequisdebian.yaml

This commit allows the user to provide a list of local files to upload to the machines (upload_files variable in the inventory). This can allow to override a script or provide a file needed on a specific setup.
This task is called at the end of the prerequisite playbook so that it can override files created by this playbook.

Upload custom files to machines

---

README.adoc

Fix typos in the section "Update a machine section", a dash was missing for the extra vars option, and it's not possible to give extra vars two options at once, so we have to use it twice.

README.adoc: fix typo in update a machine section

---

examples/inventories/advanced_inventory_cluster_example.yaml
examples/inventories/advanced_inventory_standalone_example.yaml
examples/inventories/inventory_example.yaml
examples/playbooks/vm/create.yaml
examples/vm_templates/vm_template_example.xml.j2
examples/vm_templates/vm_template_example_generic.xml.j2
roles/seapath_import_vm_disk/meta/main.yml
roles/seapath_manage_disks/meta/main.yml
roles/seapath_vm_manage/meta/main.yml
templates/vm/vm.xml.j2
templates/vm/vm_dpdk.xml.j2
templates/vm/vm_dpdk_isolated.xml.j2
templates/vm/vm_rt_dpdk.xml.j2
templates/vm/vm_rt_isolated.xml.j2
tests/add_vm_from_template.yaml
tests/vm_template.xml.j2

Remove all votp references in files or file names.
Two references remains :
- votp-config_ovs service
- votp-test-sync service.
This must be changed in meta-seapath first.

Remove votp references

---

roles/debian/physical_machine/tasks/main.yml

This commit move the sysctl customization to the beginning of the role so that other tasks can benefit from the sysctl changes

physical machine: move sysctl changes before the rest

---

inventories/seapath_vm_definition_example.yml
playbooks/deploy_vms_standalone.yaml
templates/vm/guest.xml.j2

Some VM images can be archived using gzip to reduce the size during the deployment. When setting the ansible variable `disk_extract` to true, the image disk is copied and unarchived on the target.

playbooks: deploy_vms_standalone: add gziped image support

---

ansible-requirements.yaml
inventories/seapath_cluster_definition_example.yml
roles/debian/hypervisor/tasks/main.yml

[Set corosync priority to OTHER (nice -20) instead of RR99](https://github.com/seapath/ansible/commit/a48d547642daa3ca1d86b0708aaf20bf3ad1be40)
Following this discussion, I suggest we try to run corosync with a non
realtime priority.
https://github.com/corosync/corosync/issues/706
https://github.com/seapath/corosync-ansible/commit/5a79638389916ae159312d365a40b038b9c3c6bf
----
[Makes isolation configuration revertable](https://github.com/seapath/ansible/commit/4412952ed7e33fb685f1e4fe35faffe0f08b2b52)

Corosync priority + isolation settings revertable

---

playbooks/ci_vms_standalone_ptp.yaml
src/phc2sys.service

Synchronize the system clock of each vms with phc2sys.

ci_vms_standalone_ptp.yaml: add vm ptp clock synchronisation in the CI

---

inventories/seapath_cluster_definition_example.yml
playbooks/cluster_setup_network.yaml

This commits allow the seapath user to use a template instead of a static file for the iptables rules.

iptables: add the possibility to use a jinja2 template

---

playbooks/deploy_vms_cluster.yaml
playbooks/deploy_vms_standalone.yaml

On :
- deploy_vms_cluster.yaml
- deploy_vms_standalone.yaml 
This is particularly useful when we want to start another playbook on the VM, directly after this one.

Wait for VM to be online     

---

templates/vm/guest.xml.j2

If a VM has the RT features, it has to be put in the cgroup `/machine.slice/machine-rt.slice`. If not, it has to be put in `/machine.slice/machine-nort.slice`.
This commit corrects a bug in the xml file, RT VMs were not put in the RT slice.
It also puts non-RT VMs in the nort slice.

guest.xml.j2: correct vm slice

---

README.adoc

When using the repo there can be a misunderstanding of using the main branch with Seapath Debian and debian-mai branch with Seapath Yocto. This commit adds a subsection to ensure user is using the correct branch depending of it version of Seapath.

README: add a subsection on Ansible repo branch

---

roles/debian/physical_machine/tasks/main.yml

The snmpd service is enabled by default by the debian installer. This commit disables it when the variable `snmp_admin_ip_addr` is not needed.

roles/debian: disable snmp if it is not needed

---

roles/debian/hypervisor/tasks/main.yml

the name of the variable to check is cpusystem, no cpuset

hypervisor role: typo in cpusystem variable name

---

ansible-requirements.yaml
inventories/README.md
inventories/seapath_cluster_definition_example.yml
inventories/seapath_standalone_definition_example.yml
inventories/seapath_vm_definition_example.yml
playbooks/cluster_setup_network.yaml

Reload systemd-network only when the configuration has changed.
Correct a bug where timemaster could wait for a interface that would be created later in the playbook.

Correct network playbook reboot debian

---

ansible-requirements.yaml
playbooks/cluster_setup_network.yaml

This PR backports the work done on Debian in #447 
It resolves a bug on timemaster launch #422 and correct the reboot behavior of the network playbooks

Backport debian network configuration

---

inventories/seapath_cluster_definition_example.yml
templates/systemd-networkd-wait-online.service.j2

By default, systemd-networkd-wait-online will wait for br0 (or the vlan on br0 if using br0vlan variable) and the cluster_network interface (team0 or hsr0).
In some setups it is useful to customize the network_interface the most relevant to wait for at boot time.
This new variable will override "br0" as the name of the interface we will wait for.

networkd-wait: allows the user to customize the interface to wait for

---

inventories/seapath_vm_definition_example.yml

These two variables are mandatory.

seapath_vm_definition_example: add variables

---

src/debian/snmp/exposeseapathsnmp.py
src/debian/snmp/snmp_getdata.py

This commit improves the exposed data with snmp.
It creates 5 branch in the base tree:
.1 --> any multiline values: basically a retro compatibility thing for all the stuff we used to expose with the old "net-snmp extend" snmp logic
.2 --> monoline values: with the sub tree:
- .2.[1-4] --> smart self assessement for /dev/sd[a-d]
- .2.5 -->lvs full status
- .2.5.0 --> column name
- .2.5.1 --> first LV data
- .2.5.2 --> second LV data, etc
.3 --> raid/arcconf values (if the arcconf binary is present): for setup with an adaptec raid card
.4 --> ipmi data (if the ipmitool binary is present)
.5 --> "disk need to be replaced" values:
- .5.[1-4]: informs if there is any suspiscion that the specified disk (1 to 4) must be changed
- .5.5: informs if there is any suspiscion that one of the disks …

snmp improvement

---

examples/inventories/advanced_inventory_cluster_example.yaml
playbooks/cluster_setup_add_livemigration_user.yaml
playbooks/deploy_vms_cluster.yaml

Correct a bug on the livemigration playbook.
Remove two variables in the inventory. The livemigration user is now only handled by the variable `livemigration_user`.

Harmonize livemigration yocto

---

src/tuned/tuned.conf.j2

To limit the amount of kernel logging printing directly to the console
\+ the lvm snapshot rebooter in place in the CI is not compatible with printk.devkmsg=off, we need to remove this option asap for the CI to be functionnal again.

tuned: change printk settings

---

inventories/seapath_demo_cluster_definition_example.yml

Modification corrolated to the commit 882ddd54a5f1152c628b903a25999b6a2d57816d
In the demo cluster, cluster_protocol and cluster_ip_addr are not defined. So, systemd-networkd-wait-online was waiting for all interfaces to be configured whereas it should only be waiting for br0.

seapath_demo_cluster_example: add interface to wait for at boot time

---

.github/workflows/ci-yocto.yml

Fixed the name of the VM test call that was changed in the launch-yocto.sh script.

ci-yocto.yml: fix VMs tests call

---

playbooks/ci_latency_tests.yaml

Incorporate system nice capability into VMs and publisher containers to grant the necessary capabilities for adjusting scheduling priority and policy within the container.

ci_latency_tests: add SYS_NICE capability in Docker Run

---

playbooks/cluster_setup_ceph.yaml

This playbook doesn't handle the case where lvm_volumes is not defined. This commit corrects that and consider that when lvm_volumes is not defined, it means that two disks are used : one for Linux and one for ceph.

cluster_setup_ceph.yaml: make lvm_volumes optional

---

inventories/seapath_vm_definition_example.yml
playbooks/deploy_vms_standalone.yaml

The main qcow2 file is now automatically added to the local_disk list.
It allows the VM to boot without having to declare the disk in the VM
inventory.

Autodetect vm main disk in standalone

---

.github/workflows/ci-yocto-weekly.yml
playbooks/ci_latency_tests.yaml

Delete the pcap_loop default value to a system where the number of loops must be supplied. And set of 6000 iterations for the weekly CI.

pcap_loop: add longer latency test for the weekly CI

---

prepare.sh

If the collection already exists, we need this option to force the upgrade to the new version.

prepare.sh: force update of ansible collections

---

.github/workflows/ansible-lint-debian-weekly.yml
.github/workflows/ansible-lint-debian.yml
.github/workflows/ci-debian-weekly.yml
.github/workflows/ci-debian.yml

Restrict permissions of the CI workflows:
- `actions: write` allows cancelling the workflow if a cukinia test fails
- `checks: write` allows validating the check.

.github/workflows: restrict permissions

---

inventories/seapath_vm_definition_example.yml
playbooks/deploy_vms_standalone.yaml
templates/vm/guest.xml.j2

Add the standalone main disk automatically to the libvirt XML.
Previous version use the `local_disk` variable, but the behaviour is not scalable to multiple VMs

Correct standalone VM main disk creation

---

playbooks/ci_latency_tests.yaml

The next play had no name, so the play synchronized machine with ptp was skipped.

ci_latency_tests: fix synchronise machine with ptp play

---

playbooks/ci_latency_tests.yaml

Previously we used the Ansible built-in file transfer method, but it wasn't sufficient for long time tests so we decided to use rsync instead.

ci_latency_tests: change file transfer method

---

inventories/seapath_cluster_definition_example.yml
playbooks/cluster_setup_network.yaml
roles/debian/hypervisor/tasks/main.yml
src/conntrackd/conntrackd.conf.j2

Adds optional conntrackd synchronization feature.
This is useful when using the hosts as routers (when using iptables for flow security between bridges), if you want the conntrack tables to be synchronized among hosts. This is necessary because when the default gateways for the routed networks migrate, the connection tracking status is lost.
If conntrackd_ip_list is defined it will enable the appropriate portion of the playbook, and the content will be used as the list of IP addresses to enable conntrack synchronization on.

introducing conntrackd for conntrack table synchronization

---

playbooks/cluster_setup_network.yaml
roles/debian/hypervisor/tasks/main.yml
src/debian/conntrackd_override.conf

remove apt dynamic installation of tuned and conntrackd
since the packages are preinstalled with build_debian_iso and that the CI has been upgraded with those packages
----
Make sure conntrackd is stopped/disabled if not useful
----
conntrackd.service: adds dependancy to network.online
to make sure team0 is up and running before starting conntrackd

conntrackd cleanup and bugfix

---

playbooks/cluster_setup_add_livemigration_user.yaml

The livemigration user is not created on observers. It's key should not be transmitted to observers.

cluster_setup_add_livemigration_user: use only hypervisors

---

ansible.cfg

False is not a valid value for the gathering option. The correct value is explicit. Ansible version greater than 2.10 will raise an error if the value is set to False.

ansible.cfg: set gathering to explicit

---

prepare.sh

Bash doesn't perform expansion inside a $() sub-shell. Characters between the parentheses are not treated specially, they are all passed to the sub-shell.
Therefore, inner quotes must not be escaped.
Backslashes are given as-is to the inner sub-shell, and the readlink command will get \"$0"\ as parameter, and not "$0". When calling this script from a different directory, readlink will return an empty string, and dirname will return ".", no matter the original working directory.

prepare.sh: fix expansion in subshells

---

playbooks/cluster_setup_ceph_expansion.yaml

Regex were not designed to handle devices with numbers in the middle, making it impossible to install Ceph on nvme disks.

cluster_setup_ceph: fix installation on NVMe disks

---

.cqfd/docker/Dockerfile

Npm is used to build the Cockpit plugin (dashboard, update, vm management) before installing them on hypervisors.

Dockerfile: add nodeJS package manager

---

templates/timemaster.conf.j2

Remove use of obsolete ntp_primary_server and ntp_secondary_server variables.
The list ntp_servers should be used instead.

templates: timemaster.conf.j2: only configure NTP with ntp_servers

---

.github/workflows/ci-yocto.yml

Allows to trigger the ci without making a pull request

ci-yocto: add workflow dispatching

---

inventories/seapath_cluster_definition_example.yml
inventories/seapath_standalone_definition_example.yml
playbooks/cluster_setup_network.yaml

Add iptables feature to standalone
The iptables feature that allows the seapath user to use a template or a static file to load iptables rules was not available for standalone architecture. This fixes this issue.
----
Add option to upload user hosts file
A hosts file can be provided to add local name resolution. Indeed there will most probably be no DNS in a substation.
This file is specified using the hosts_path variable and can be either a plain text file or a Jinja template.

Add hosts file upload to cluster and standalone architecture and iptables rules feature to standalone architecture

---

playbooks/deploy_vms_cluster.yaml
playbooks/tasks/deploy_vm.yaml

* vm_file can also be defined in the VM hostvars
* vm_file_dest have a default value: /tmp/os_[vm name].qcow2
* disk_copy is true by default
* live_migration is false by default instead of empty string

playbooks/tasks/deploy_vm.yaml: change default value

---

examples/inventories/advanced_inventory_cluster_example.yaml
examples/inventories/advanced_inventory_standalone_example.yaml
examples/inventories/netplan_admin_br0_example.yaml.j2
examples/inventories/netplan_cluster_example.yaml.j2
examples/inventories/netplan_ptp_interface_example.yaml.j2
examples/inventories/vms_inventory_example.yaml
examples/vm_templates/vm_template_example.xml.j2
examples/vm_templates/vm_template_example_generic.xml.j2
playbooks/cluster_setup_add_livemigration_user.yaml
playbooks/cluster_setup_ceph.yaml
playbooks/cluster_setup_configure_hugepages.yaml
playbooks/cluster_setup_libvirt.yaml
playbooks/deploy_vms_cluster.yaml
templates/vm/vm.xml.j2
templates/vm/vm_dpdk.xml.j2
templates/vm/vm_dpdk_isolated.xml.j2
templates/vm/vm_rt_dpdk.xml.j2
templates/vm/vm_rt_isolated.xml.j2
tests/add_vm_from_template.yaml
tests/vm_template.xml.j2
vars/network_vars.yml

The copyright of the files was not correct. It was written as SFL instead of Savoir-faire Linux, Inc.

fix Savoir-faire Linux copyright

---

module_documentation_sources/requirements.txt

Old Pygments version have vulnerabilities:
* CVE-2021-20270
* CVE-2021-27291
* CVE-2022-40896

module_documentation_source: bump Pygments version to 2.18.0 or greater

---

playbooks/cluster_setup_network.yaml
playbooks/cluster_setup_prerequisdebian.yaml
playbooks/deploy_vms_standalone.yaml
roles/debian/physical_machine/tasks/main.yml

- Build the hosts file, and use ansible_host as a fallback if ip_addr is not defined.
- Push hosts file is now available for VMs.
- haclient group is only in cluster_machines: Moved out from physical_machines.
- Refactor playbook deploy_vms_standalone to use loop and fix variable usage
- Changed with_items to loop for consistency and modern Ansible practices
- Use force variable to upload an already running VM as in deploy_vms_cluster
- Use enable variable to start a VM as in deploy_vms_cluster

Changes in cluster_setup_network and prerequisdebian + Refactor playbook deploy_vms_standalone

---

playbooks/cluster_setup_network.yaml

When removing and recreating team0, conntrackd needs to be restarted to take the new team0 into account.
If at the same time the configuration has changed, the change in configuration will only occur later in the playbook, so this restart will be done with the previous version of the configuration, which can be not working (hence the need to change the configuration).
This commit will make this first conntrackd restart operation ignore the error just in this case.

ignore errors when restarting conntrackd after recreating team0

---

inventories/seapath_cluster_definition_example.yml
inventories/seapath_standalone_definition_example.yml
vars/network_vars.yml

The "subnet" variable is used for 2 distincts interfaces : br0 and team0.
This commit creates the team0subnet variable to be used for team0 (cluster network).

team0 subnet: split from br0 subnet

---

inventories/seapath_cluster_definition_example.yml
inventories/seapath_standalone_definition_example.yml
playbooks/cluster_setup_prerequisdebian.yaml

If the user uses the upload_files variable to upload custom files at the end of the playbook, he might need to restart a service or something similar.
This commits allow the user to use the commands_to_run_after_upload to run any commands he likes after uploading custom files.

allow the user to run commands after uploading custom files

---

templates/timemaster.conf.j2

After PTP becomes unavaillable, chrony still selects it for a time period :
> Reachability is not a requirement for selection. An unreachable source
> can still be selected if its newest sample is not older than the oldest
> sample from reachable sources.
This period is defined by the number of samples and the polling period and is, by default, highly variable (up to 10*1024s=~3h).
Set min/max for poll and sample for make this period more predictable:
* poll = 6 => 2^6=64 seconds poll periode
* sample = 10
So, the PTP->NTP fallback time around 11 minutes (10*64s)
CC: @insatomcat

timemaster: limit PTP->NTP fallback time

---

examples/inventories/advanced_inventory_standalone_example.yaml
playbooks/cluster_setup_kernel_params.yaml
src/find_boot_partition.sh

The boot partition was search with the boot label. This works on BIOS
setup, but not on uefi setup.
This PR corrects this behavior and add documentation.
Closes #361

Correct boot mount

---

roles/timemaster/templates/timemaster.conf.j2

In ptp4l, the default timeout to get the TX timestamp (1 ms) might be low on a loaded system For example, with IGB driver, a kworker (SCHED_OTHER) wakeup is on the critical path and may have to wait a tick to be scheduled.
Increase this timeout to 10ms to give the kworker thread a chance to be schedule at a tick.

timemaster/ptp4l: increase timeout to avoid warnings on loaded systems

---

.github/workflows/ci-debian-weekly.yml

The debian branch is now debiancentos and not debian-main.

ci-debian-weekly.yml: run on debiancentos

---

roles/centos_physical_machine/tasks/main.yml
roles/centos_physical_machine/templates/pacemaker_override.conf.j2
roles/debian_physical_machine/files/libvirtd_override.conf
roles/debian_physical_machine/tasks/main.yml
roles/debian_physical_machine/templates/pacemaker_override.conf.j2

On standalone, the VMs are not started/shutdown with pacemaker, so we need to use the autostart feature of libvirtd. It seems that this "virsh list" as ExecStartPost makes libvirtd choke on autostart.
This "virsh list" was there to make sure libvirtd is properly started before we start pacemaker.
This commits moves this check as an ExecStartPre of pacemaker, so that it does not meddle with libvirtd startup.
This will solves #613.

Solves VMs autostart on standalone

---

inventories/netplan_ovs_bridge_example.yaml.j2
inventories/seapath_vm_definition_example.yml
templates/vm/guest.xml.j2

This PR adds new ways to managed OVS bridges and virtual port through Netplan and Libvirt, on a standalone Seapath machine.
* Using Netplan configuration file [inventories/netplan_ovs_bridge_example.yaml.j2](https://github.com/seapath/ansible/compare/debiancentos...netplan_ovs?expand=1#diff-4ddaad927cd1722f5584e18d4e721c6983495a0cc458ee47d77712c3170e040b), it is now possible to create an OVS bridge from Netplan.
* Using Libvirt <virtualport> field, it is now possible to create OVS virtual port directly from Libvirt XML configuration file. The modification adds also the possibility to configure a VLAN. 
These modifications are based on the current inventory OVS bridge  syntax.

OVS management through Netplan and Libvirt

---

roles/debian_physical_machine/files/pacemaker_ra/VirtualDomain

This patch adds the support of the "sync_config_on_stop parameter" when "seapath" parameter is set to "true".
When the "sync_config_on_stop" parameter is set to "true", the domain configuration is saved to the rbd image metadata when the resource is stopped.
The sync config validates the XML configuration and requires libxml2-utils packages installed by this PR: https://github.com/seapath/build_debian_iso/pull/117.

pacemaker_ra/VirtualDomain: add support of sync_config_on_stop

---

playbooks/seapath_setup_prerequisdebian.yaml

The command module does not support advanced Bash operations such as pipes (|), redirections, or if conditionals. That’s why the use of the shell module is necessary in this case.
My use case was: I need to restart a pacemaker resource after file upload and needed this command to run only on node 1. "if [[ $(hostname) == 'node1' ]] && crm_mon -1 | grep 'my_resource'; then crm_resource --resource my_resource --restart; fi"

Allow advanced commands after file upload

---

playbooks/cluster_setup_ha.yaml

This commit only restarts corosync when needed (the corosync.conf file has changed).

HA playbook: prevent automatic restart of corosync

---

playbooks/ci_prepare_VMs.yaml

Apply realtime-virtual-guest inside the Debian virtual machines. When not applied, hours-long cyclictest have a maximum latency over 10ms.
This commit also creates a new debian/vm roles for this purpose.
Closes #529

Apply tuned profile to VM

---

playbooks/cluster_setup_add_livemigration_user.yaml

Fix the root path and the livemigration use groups.

Cluster setup add livemigration user fixes

---

.cqfd/docker/Dockerfile
.gitmodules
ansible-requirements.yaml
prepare.sh
src/ceph-ansible-patches/distro_not_supported.diff
src/ceph-ansible-patches/osd_no_package.diff

The Ceph and ceph-ansible have to be in the same version. This patch moves ceph-ansible to the ceph 16 version to match the ceph version.
This patch upadtes the ceph-ansible submodule, the ansible-requirements.yaml file to match the new ceph-ansible requirements and update the patches.

ceph-ansible: move to ceph 16

---

prepare.sh

The error message for the Ansible version check was incorrect. It was checking for version 2.10 but the error message was saying that the version must match 2.9.

prepare: fix error message for Ansible version

---

playbooks/replace_machine_remove_machine_from_cluster.yaml
playbooks/replace_machine_shrink_mon.yaml

This commits uses the "hostname" variable to remove the ceph components in the replace machine playbook, in case the actual hostname of the node is different from the inventory hostname (in which case the ceph component will not be called after the inventory hostname)

replace node: allow for custom hostname different than inventory hostname

---

.gitignore
playbooks/purge_ceph.yaml

This playbook allows to remove configurations related to Ceph to re-deploy a cluster.

purge_cluster: add playbook to purge Ceph

---

playbooks/cluster_setup_add_livemigration_user.yaml

The authorized_keys file is now created in the default path for the livemigration_user. This is done to avoid the need to specify the path in the playbook.

livemigration_user: use default path for authorized_keys

---

.github/workflows/ci-debian-weekly.yml
.github/workflows/ci-yocto-weekly.yml
.github/workflows/ci-yocto.yml

This patch adds a condition to the jobs that launch the tests to make sure all the tests are run even if the previous step failed. Without this condition, the tests would not run if the previous step failed and the report generation would fail.

github/workflows: keep running tests even if the previous step failed

---

ansible-requirements.yaml

The latest commit of the systemd_networkd role use udevadm trigger to re-trigger udev rules after the networkd configuration is applied instead restarting the udev service.

ansible-requirements: bump systemd_networkd role to latest commit

---

playbooks/seapath_setup_main.yaml

Currently, seapath_setup_prerequiscentos.yaml and
seapath_setup_prerequisdebian.yaml playbooks have tasks applying to VMs. As "when" conditions on "import_playbook" are evaluated for every task in the playbook, "when" conditions on seapath_distro in seapath_setup_main.yaml will be evaluated on VMs tasks. To prevent undefined variable errors, also detect the seapath distro on VMs.
If VMs in the inventory are not reachable because not yet deployed, or doesn't match any seapath_dsitro criteria, they should be ignored with the appropriate `--limit` option when executing seapath_setup_main.yaml, as stated in README.adoc.

playbooks/seapath_setup_main.yaml: detect seapath distro for VMs

---

inventories/providers/abb/ssc600_hypervisor_standalone_example.yaml

The cpu isolation is needed for the vm. Add it to the example inventory.

Isolcpu ssc600 debian

---

.github/workflows/ci-debian.yml

The `workflow_dispatch` allows to manually trigger the CI, in particular on a specific branch of the CI repository.

github/workflows/ci-debian: add workflow_dispatch

---

roles/ci_yocto/get_system_info/files/get_system_info.py

get_system_info.py retrieves Network information which is too large to output in a pdf report.
Drop it for the moment.

ci: remove network information

---

.github/workflows/ci-yocto-weekly.yml
.github/workflows/ci-yocto.yml
playbooks/ci_latency_tests.yaml

- Run latency test for 5H
- Save only the latency of the first SV of each 4000 iteration as a temporary workaround due to current memory limitations

Improve latency tests

---

playbooks/ci_prepare_VMs.yaml
roles/debian/tasks/main.yml
roles/deploy_vms_cluster/tasks/main.yml
roles/deploy_vms_standalone/tasks/main.yml

prevent removal of /tmp sticky bit
----
debian vm: do not disable chrony
In the CI, the VMs need to be synchronised with ptp-kvm, which requires chrony

prevent removal of /tmp sticky bit + debian vm: do not disable chrony

---

playbooks/ci_all_machines_tests.yaml
playbooks/ci_standalone_setup.yaml
roles/ci_yocto/clean_arm_machines/tasks/main.yaml
roles/ci_yocto/get_system_info/tasks/main.yaml
roles/ci_yocto/run_tests/tasks/main.yaml

The reboot_on_usb_drive have been replaced by clean_arm_machines on arm machines. This is mandatory since there is no solution to flash the board yet.
The cyclictest have been removed since the kernel is not RT.
Get_system_info have been modified so that multiple system_info can be generated with different names.

ci_yocto: add support for Aaeon I.MX8 board

---

roles/timemaster/templates/timemaster.service.j2

"After" setting should be in the Unit section of a systemd service file.

roles/timemaster: fix After setting

---

roles/debian_hypervisor/tasks/main.yml

Currently, when deploying a SEAPATH Debian standalone configuration some tasks failed has it requires team0 network, which is not used on a standalone configuration (only cluster).
This issue has been introduced with commit
3691fb2f8896c573a962b8ee3714340e53e7d2d7 from PR
https://github.com/seapath/ansible/pull/666.
A missing `when` condition is needed to run these tasks only if team0 network is used.

debian_hypervisor: add missing team0 condition

---

roles/configure_libvirt/tasks/main.yml

Following 2ffef3b1b0da314798efe6bb5802368ae7f69030
When running tasks on cluster hypervisors (members of cluster_machines and hypervisors groups), any "looped" action must also be restricted to the same intersection of groups
Also we put the when condition before the block keyword, which is an ansible standard enforced by newest version of ansible-lint.

fix bug in loops on cluster hypervisors

---

roles/deploy_cukinia_tests/tasks/main.yml

If the user running ansible-playbook is not root, the owner of the copied files will be the user running the playbook. This is not desirable, as the files should be owned by root.

deploy_cukinia_tests: fix owner of copied files

---

roles/centos/tasks/main.yml
roles/ci_restore_snapshot/tasks/main.yml

1. When restoring the LVM snapshot the snapshot partition is not immediately gone after reboot, a race condition exists between the ansible runner getting to the "Recreate the snapshot" stage and the target machine syncing the LVM partitions and removing the snapshot, on a slower machine this will cause the ansible to try and create an root-snapshot partition and receiving the error  "Operation not permitted on hidden LV vg1/root-snap", the solution is to wait for the root-snap partition to be cleared.
2. CentOS natively uses NetworkManager as the network service, SEAPATH does not at the moment support this, we use systemd-networkd, for the network to be properly configured NetworkManager must be shot down and systemd-networkd enabled and started, if that was not the case to begin with, a …

Bug fixs from CI testing

---

.gitmodules
roles/deploy_python3_setup_ovs/files/seapath-config_ovs.service
roles/deploy_python3_setup_ovs/tasks/main.yml
roles/network_configovs/vars/CentOS.yml
roles/network_configovs/vars/Debian.yml
roles/network_configovs/vars/Yocto.yml

Switch setup_ovs installation to pip-based instead of the deprecated setup.py
This prevents a warning with python 3.12

Switch setup_ovs installation to pip-based instead of the deprecated setup.py

---

.gitmodules
roles/deploy_vm_manager/tasks/main.yml

Switch vm_manager installation to pip-based instead of the deprecated setup.py
This prevents a warning with python 3.12

Switch vm_manager installation to pip-based instead of the deprecated setup.py

---

roles/debian_hardening_physical_machine/files/pacemaker_hardening.conf

Without this, hardening prevents live-migration from working

debian hardening: add cap_setpcap to pacemaker

---

roles/debian_physical_machine/handlers/main.yml
roles/debian_physical_machine/tasks/main.yml

Dracut is for CentOS
Debian uses initramfs

Debian: fix typo in initramfs rebuild handler

---

roles/ci_yocto/clean_arm_machines/tasks/main.yaml

The logs are not cleaned after the update of the ARM machines in the CI. This can lead to a full log partition and the machine will not be able to run the tests.
This patch adds the cleaning of the journal and syslog-ng logs after the update of the ARM machines in the CI.

ci_yocto: clean the log after update in the ARM CI

---

roles/deploy_python3_setup_ovs/tasks/main.yml
roles/deploy_vm_manager/tasks/main.yml

Otherwise, pip does not see python3-setuptools and tries to download it, which requires internet access.

debian/pip: need --no-build-isolation

---

roles/configure_ha/README.md
roles/configure_ha/defaults/main.yml
roles/configure_ha/tasks/main.yml

enable_vmmgr_api_http is a variable mostly related to the vmmgrapi role, this is not a "configure_ha" variable.
This was renamed because of ansible lint and the fact that a default was set for this variable in the configure_ha role.
This commit removes the default, renames the variable back to before, and set a "is defined" condition in the configure_ha role which has the same effect as having a "false" default.

configure_ha: rollback renaming enable_vmmgr_api_http

---

templates/vm/guest.xml.j2

This is an alias to the default q35 machine, so this approach is more portable.

vm template: use "q35" machine type

---

roles/timemaster/tasks/main.yml

Sometimes the unit is present in the list of services even though the service is not on the node, in which case it has a "not found" status. This commit makes sure the unit is actually present.

systemd unit: add not "not-found" condition

---

roles/network_resolved/tasks/main.yml

On SEAPATH Yocto, libvirt installs as dependency dnsmasq. dnsmasq.service is then started along libvirtd and requires /etc/resolv.conf to exist, or be a link to an existing file.
However, /etc/resolv.conf points to /run/systemd/resolve/resolv.conf, which is created by the systemd-resolved service.
If systemd-resolved is disabled, dnsmasq will also fail because /etc/resolv.conf points to nothing, and the cukinia test checking for failed service will fail.
As a temporary workaround to prevent dnsmasq.service failure on Yocto, do not disable systemd-resolved.service even when no dns server is specified.

roles/network_resolved: do not disable systemd-resolved on Yocto

---

.github/workflows/ci-debian.yml

These tests are obsolete and will be replaced by the newest svtrace approach

Debian: remove latency testing

---

inventories/examples/seapath-vm-deployement.yaml
inventories/providers/abb/README.md
inventories/providers/abb/ssc600_hypervisor_standalone_example.yaml
inventories/providers/abb/ssc600_vm_example.yaml
playbooks/seapath_setup_prerequisyocto.yaml

- Correct a bug on kernel parameter modification on Yocto
- Refactor ABB SSC600SW inventory examples
- Only propose to use qcow2 files in the examples (no img.gz)

bugfix and ABB SSC600SW example refactoring

---

README.adoc
ansible.cfg

Configure ansible.cfg to run each ansible-playbook commands with --skip-tags "package-install" set by default.

ansible.cfg: run --skip-tags "package-install" by default

---

inventories/examples/seapath-vm-deployement.yaml
templates/vm/guest.xml.j2
templates/vm/seapath_guest_nort.xml.j2
templates/vm/seapath_guest_rt.xml.j2
templates/vm/ssc600.xml.j2

Add the "vm_features" secure-boot in VM's configurations templates to explicitly enable or disable the secure boot.
Without this feature, the secure boot enabling differs between hypervisor machines and can lead to unexpected behaviors.

templates/vm: add secure boot feature

---

playbooks/ci_test.yaml
playbooks/test_deploy_cukinia_tests.yaml

Call the deploy_cukinia role in the test_deploy_cukinia_tests playbook. Remove the deploy_cukinia role from the ci_test playbook.

test_deploy_cukinia_tests: add deploy_cukinia role to the playbook

---

inventories/examples/seapath-standalone.yaml

The interfaces_to_wait_for variable should be a list of interfaces to wait for.

inventories/examples/seapath-standalone: fix interfaces_to_wait_for

---

.github/workflows/ci-yocto-weekly.yml
.github/workflows/ci-yocto.yml

Add the execution of seapath-benchmark in Yocto weekly CI.

ci-yocto: add seapath benchmark execution

---

playbooks/seapath_setup_main.yaml
playbooks/seapath_setup_prerequisdebian.yaml
playbooks/seapath_setup_vmmgrapi.yaml
roles/configure_ha/README.md
roles/configure_ha/tasks/main.yml
roles/vmmgrapi/README.md
roles/vmmgrapi/defaults/main.yml
roles/vmmgrapi/tasks/main.yml
roles/vmmgrapi/templates/nginx.conf.j2

Remove backup-restore on standalone
On standalone backup-restore does not make sense.
----
vmmgrapi: refactor to make it work on standalone
- admin_cluster_ip is replaced by a role variable vmmgrapi_ipaddress, specific to the vmmgrapi role
- deployment of this role is delayed to after configure_ha
- the vmmgrapi role now includes the logic to change the pacemaker configuration, instead of configure_ha

remove backup-restore and adapt vmmgrapi on standalone

---

.github/workflows/ci-yocto.yml

The seapath-benchmark task run condition was incorrect, causing it to not be run in the weekly CI run.

ci-yocto: fix incorrect condition

---

ansible-requirements.yaml

https://github.com/seapath/ansible-role-systemd-networkd/pull/8

Revert "handlers: use udevadm trigger instead of restarting udev"

---

playbooks/cluster_setup_ceph.yaml

By default, the ceph_uid variable is used by ceph-ansible to set user and group ownerships of files created on the target. For example, this is the case for the Ceph keys in /etc/ceph.
Until now, its value was provided by the ceph-defaults role of ceph-ansible. It works correctly with Debian, but sets the value to 167 by default for Yocto. This creates files on the system that do not belong to any user / group.
Fix this by setting ceph_uid to the actual UID of the ceph user.
Fixes partially https://github.com/seapath/ansible/issues/695

cluster_setup_ceph: set ceph_uid variable for Yocto

---

inventories/providers/abb/README.md

On strict markdown parsers, the README file was not correctly rendered. This commit fixes the syntax to have a better rendering.

inventories/providers/abb/README: fix markdown syntax

---

roles/snmp/templates/snmpd.conf.j2

The perl snmp agent seems unstable after a few fays of running time. It still runs but does not update the snmp tree anymore. We fix this by forcing snmpd to reload it after 1h, so that it stays fresh.

snmp agent: reload after 1h

---

roles/snmp/files/exposeseapathsnmp.pl

If the cron job that get the snmp data and the expose script have the same interval (currently 300s = 5min), we encounter the risk that the generation of the snmp data file and the reading of that file always happen at the same time...
This commit set the interval of the expose script to 4min, so that we are sure those scripts don't run at the same time.

expose snmp data: have a different interval than the cron job

---

roles/snmp/files/exposeseapathsnmp.pl
roles/snmp/files/seapathsnmp.cron
roles/snmp/files/snmp_getdata.py
roles/snmp/tasks/main.yml
roles/snmp/templates/snmpd.conf.j2
roles/snmp/templates/sudoers_snmp.j2

We have a "get snmp data" script and an "expose snmp data" script. Both needs a "refresh" interval.
If both logics use the same interval, there is the risk they interfere with each other. If we set a different interval, sometime the expose script will run just after the getting of the data (and the exposed data will be fresh) or just before, in which case the data will be fresh again after 4+5min (9min). 
For the data to be always fresh, it seems best to run the get_data script just before the expose refresh, so to include it in the script. 
This makes the cron job useless, however since the expose script is run by snmp, we have to give the permission to the snmp user via sudo.

snmp: include the get snmp data logic directly into the expose script

---

playbooks/replace_machine_remove_machine_cephadm.yaml
roles/cephadm/tasks/main.yml

The replace node logic is very useful in case of a failing node.
We can replace the node by a new one and then:
- call the "remove node" logic that will remove the failed node from corosync/pacemaker and ceph clusters
- call the main playbook again which will add the new node to both clusters

Adapt "replace failed node" logic to cephadm

---

playbooks/replace_machine_remove_machine_cephadm.yaml
playbooks/seapath_setup_prerequisdebian.yaml
roles/cephadm/README.md
roles/cephadm/defaults/main.yml
roles/cephadm/tasks/main.yml
roles/debian_hypervisor/tasks/main.yml
roles/debian_tests/cukinia-tests/cukinia/common_security_tests.d/apt.conf.j2
roles/debian_tests/cukinia-tests/cukinia/common_security_tests.d/files.conf
roles/debian_tests/cukinia-tests/cukinia/common_security_tests.d/systemd.conf
roles/debian_tests/cukinia-tests/cukinia/hypervisor_security_tests.d/groups.conf.j2
roles/debian_tests/cukinia-tests/cukinia/hypervisor_security_tests.d/passwd.conf.j2

cephadm: fix on replacing first node
The current code did not work when the node to be replaced was the first one.
This commit makes it possible to replace any node.
----
cephadm: introducing cephadm_install
This is a variable to make the playbook install the cephadm binary (not compatible with offline install mode, obviously).
----
cephadm: stop depending on local ceph packages
Local ceph packages were still necessary for tools like rbd or ceph-volume.
This commit makes the maximum to use the tools provided inside the containers (ceph-volume, ceph, etc.). We will still need ceph-volume (for rbd, used by vm-manager) though.
----
cephadm: adapt debian tests for podman
----
cephadm: fix cephadm test on standalone
----
remove docker forced start
This commit removes old code from when the …

Fixes on Cephadm

---

roles/cephadm/tasks/main.yml
roles/debian_tests/cukinia-tests/cukinia/cluster_tests.d/ceph.conf

**cephadm: adapt test for containerized ceph**
The timeout executed in a subshell will make the cephadm command choke because of how signal management is interfering.
This is solved with "--foreground" in the timeout command.
man timeout:
```
--foreground
when not running timeout directly from a shell prompt,
allow COMMAND to read from the TTY and get TTY signals; in this mode, children of COMMAND will not be timed out
```
----
**cephadm: adapt ceph wrapper for case with no argument**
When no argument is passed to the "ceph" command we want to launch a cephadm shell.

cephadm: more fixes

---

roles/debian_hardening_physical_machine/tasks/main.yml

Necessary for the cephadm user to be able to run sudo, with the hardening setup

cephadm: add cephadm user to privileged group

---

inventories/examples/seapath-cluster.yaml
playbooks/cluster_setup_cephadm.yaml
playbooks/seapath_setup_main.yaml
playbooks/seapath_setup_network.yaml
playbooks/seapath_setup_prerequisdebian.yaml
roles/ceph_expansion_lv/tasks/main.yml
roles/ceph_expansion_vg/tasks/main.yml
roles/ceph_prepare_installation/tasks/main.yml
roles/debian_hardening_physical_machine/tasks/main.yml
roles/detect_seapath_distro/tasks/main.yaml
vars/network_defaults.yml

improve ceph lv creation
This is less buggy.
----
introducing is_using_cephadm variable
Instead of checking for the seapath_distro and cephadm_force variables, we set is_using_cephadm in the detect_seapath_distro role and use this variable instead, to know whether we deploy with ceph-ansible or cephadm.
----
network: allows no having a cluster network
It's useful for some test setups to not have to create a fully resilient cluster_network.
This commit allows the cluster network to use only the team0 interface instead of a team0 bridge with 2 interfaces.
For that purpose we introduce the "no_cluster_network" variable.

changes for cephadm and cluster network

---

playbooks/seapath_setup_prerequisdebian.yaml
roles/ceph_prepare_installation/tasks/main.yml
roles/cephadm/defaults/main.yml
roles/cephadm/tasks/main.yml
roles/cephadm/templates/spec.yaml.j2
roles/configure_ha/tasks/main.yml
roles/debian_tests/cukinia-tests/cukinia/common_security_tests.d/apt.conf.j2
roles/network_networkdwait/templates/systemd-networkd-wait-online.service.j2

ceph: fix LV creation
Without this commit, if the partition exists but the LV does not, the LV creation fails.
We need to make everystep independant (partition, PV, VG, LV...), but in the meantime we make everything in one unique block so that if nothing is done on the partition (first step) we don't do anything with the other steps.
----
use ceph orch spec to deploy osd
So that the OSDs are in a managed state
----
cephadm: install ceph-common package
----
cephadm: use ceph binary from distro package
----
cephadm: add cephadm package to test
----
cephadm: create the user/group before installing cephadm
Otherwise cephadm will create user and group with different UID/GID
----
cephadm: add variable for repo and ceph-command installation
----
cephadm: remove ceph-volume package
----
cephadm: …

cephadm - new fixes

---

playbooks/cluster_setup_ceph.yaml
playbooks/cluster_setup_cephadm.yaml
roles/ceph_expansion_lv/README.md
roles/ceph_expansion_vg/README.md

Fixes the case where the user choose to give ceph the whole disk, in which case lvm_volumes is not defined.

ceph: fix installation on whole disk

---

roles/debian_physical_machine/files/ethmonitor_patch1
roles/debian_physical_machine/files/ethmonitor_patch2
roles/debian_physical_machine/tasks/main.yml

The ethmonitor resource agent exists but has 2 limitations:
- no dampening feature
- needs arping installed even if not used by the configuation
This commit creates an ocf:seapath:ethmonitor overrides that deals with those two issues.
Example:
```
primitive ethmonitor-ADM ocf:seapath:ethmonitor \
params interface=ADM repeat_count=1 repeat_interval=1 link_status_only=true dampen=10s \
op monitor timeout=10 interval=10
```

pacemaker: adds ethmonitor resource agent override

---

roles/conntrackd/README.md
roles/conntrackd/defaults/main.yml
roles/conntrackd/templates/conntrackd.conf.j2

In case of "no cluster network", we can't use team0, so we need to give the option to the user to set a specific interface name.

conntrackd: variabilize interface name

---

playbooks/seapath_setup_custom_hardware.yaml
roles/hardware_customization_welotec/README.md
roles/hardware_customization_welotec/meta/main.yaml
roles/hardware_customization_welotec/tasks/main.yaml
roles/hardware_customization_welotec/vars/network_link.yaml

This playbook can be used to run tasks on custom hardware. The first role implemented is used to set up the network interfaces of a Welotec RSAPCMK2 hypervisor, based on the behavior of [1].
[1]: https://github.com/welotec/seapath-build_debian_iso/blob/main/usercustomization/scripts/USERCUSTOMIZATION/90-welotec

seapath_setup_custom_hardware: add playbook

---

roles/network_sriovpool/README.md
roles/network_sriovpool/tasks/main.yml

Variable names used in the tasks .yml file and the readme were misaligned with the variables actually supplied

Align variables and documentation for sriov pool creation

---

.gitignore
ansible-lint.conf
playbooks/seapath_update_yocto_cluster.yaml
playbooks/seapath_update_yocto_standalone.yaml

Add playbooks to update Yocto machines in standalone or cluster. These playbook are backported from the yocto_legacy branch. They were forgotten while merging yocto and debian branches together.

playbooks/seapath_update_yocto: add playbooks

---

prepare.sh

Update the prepare.sh script to fetch version 1.2.0 of the cockpit-cluster-dashboard and cockpit-cluster-vm-management plugins.

prepare: bump cockpit plugins to 1.2.0
